Ja/3/press release
selsa-inube/bootcamp pull request #323
Opened 2023-10-24 18:21 UTC by JanuarAsprilla

Correspondiente a la actividad press release

2023-10-25 00:37 UTC, wfercanas requested changes

2023-10-25 00:37 UTC, wfercanas commented on src/januar_asprilla/html-css/press-release/index.html
> +    <div class="pagina-principal">
Si es el contenido principal, es preferible usar un `<main>` que un div con class "página-principal"

2023-10-25 00:37 UTC, wfercanas commented on src/januar_asprilla/html-css/press-release/index.html
> +        </p>
Estos son dos párrafos separados. No hace falta incluirlos ambos en uno sólo y acomodar el layour usando dos `<br />` seguidos

2023-10-25 00:37 UTC, wfercanas commented on src/januar_asprilla/html-css/press-release/index.html
> +        </article>
Esto no es un artículo, parece más un texto que acompaña la fotografía. Puede usar un `<figcaption>`

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/figcaption

2023-10-25 00:37 UTC, wfercanas commented on src/januar_asprilla/html-css/press-release/index.html
> +      <br />
No utilice los `<br />` para lograr los espacios, para eso está el CSS con la propiedad de margin. Aplica para todo el documento.

2023-10-25 00:37 UTC, wfercanas commented on src/januar_asprilla/html-css/press-release/index.html
> +        <strong class="categorias">“Ted Lasso”</strong>
Esto es un texto suelto que no está conectado con la lista que sigue, cosa que no es cierta si uno revisa el documento y lo que dice.
O bien estó es un heading, o bien tanto este texto como la lista pertenecen a un grupo, que puede ser una section.

Aplica para "Ted Lasso", "Severance" y demás.

2023-10-25 00:37 UTC, wfercanas commented on src/januar_asprilla/html-css/press-release/index.html
> +          >“Carpool Karaoke: The Series”</strong
Esto parece más un encabezado en el documento original que un texto en negrilla suelto por aquí.

2023-10-25 00:37 UTC, wfercanas commented on src/januar_asprilla/html-css/press-release/assets/css/style.css
> +.comunicado {
Este texto está pegado entre renglones, así no está en el diseño original

2023-10-25 00:37 UTC, wfercanas commented on src/januar_asprilla/html-css/press-release/assets/css/style.css
> +  width: 600px;
La página principal no tiene siempre 600px de ancho. 
1. Si revisa el ancho del título del artículo, tiene 980px de ancho.
2. Si revisa el ancho de los párrafos que van después de la foto, usan 653px de ancho.

2023-10-25 00:37 UTC, wfercanas commented on src/januar_asprilla/html-css/press-release/assets/css/style.css
> +  color: #303030;
El texto está más comprimido entre renglones en comparación con el original. En el original el texto tiene un `line-height` diferente.

2023-10-25 00:37 UTC, wfercanas commented on src/januar_asprilla/html-css/press-release/assets/css/style.css
> +  font-size: 18.5px;
Este no es el tamaño de fuente que utiliza el documento.

2023-10-25 00:37 UTC, wfercanas commented on src/januar_asprilla/html-css/press-release/assets/css/style.css
> +  font-size: 17px;
Este no es el font-size que tienen los títulos. En el original están más grandes.

2023-10-25 00:37 UTC, wfercanas commented on src/januar_asprilla/html-css/press-release/assets/css/style.css
> +li {
Los elementos de las listas están comprimidos, aparece uno encima del otro muy de cerca. En el original hay mayor espaciado entre elementos.
Quizá convenga revisar el `font-size` de esos ítems o el `line-height` como en la clase `.texto`.

2023-10-25 03:10 UTC, JanuarAsprilla commented on src/januar_asprilla/html-css/press-release/index.html
> +    <div class="pagina-principal">
corregido

2023-10-25 03:11 UTC, JanuarAsprilla commented on src/januar_asprilla/html-css/press-release/index.html
> +        </p>
corregido

2023-10-25 03:16 UTC, JanuarAsprilla commented on src/januar_asprilla/html-css/press-release/index.html
> +    <div class="pagina-principal">
corregido

2023-10-25 03:17 UTC, JanuarAsprilla commented on src/januar_asprilla/html-css/press-release/index.html
> +        </article>
corregido

2023-10-25 03:22 UTC, JanuarAsprilla commented on src/januar_asprilla/html-css/press-release/index.html
> +      <br />
corregido

2023-10-25 03:29 UTC, JanuarAsprilla commented on src/januar_asprilla/html-css/press-release/index.html
> +        <strong class="categorias">“Ted Lasso”</strong>
corregido

2023-10-25 03:35 UTC, JanuarAsprilla commented on src/januar_asprilla/html-css/press-release/index.html
> +          >“Carpool Karaoke: The Series”</strong
corregido

2023-10-26 03:49 UTC, wfercanas commented on src/januar_asprilla/html-css/press-release/index.html
> +      <br />
Aún falta eliminar algunos `<br />` del documento.

2023-10-26 03:50 UTC, wfercanas commented on src/januar_asprilla/html-css/press-release/assets/css/style.css
> +  width: 600px;
Dejó todo el ancho a 790px y no el artículo no es así. Use los anchos que le mencioné en este comentario.

2023-10-26 03:51 UTC, wfercanas commented on src/januar_asprilla/html-css/press-release/assets/css/style.css
> +  font-size: 18.5px;
Realmente el font-size es 19px

2023-10-26 03:51 UTC, wfercanas commented on src/januar_asprilla/html-css/press-release/assets/css/style.css
> +li {
Con colocar el font-size de 19px para los li, ya debería funcionar correctamente.

2023-10-26 05:16 UTC, JanuarAsprilla commented on src/januar_asprilla/html-css/press-release/index.html
> +      <br />
listo

2023-10-26 05:27 UTC, JanuarAsprilla commented on src/januar_asprilla/html-css/press-release/assets/css/style.css
> +li {
listo

2023-10-26 05:35 UTC, JanuarAsprilla commented on src/januar_asprilla/html-css/press-release/assets/css/style.css
> +  width: 600px;
listo

2023-10-31 18:54 UTC, merged