Ja/5/pseudoclasses and pseudoelements
selsa-inube/bootcamp pull request #330
Opened 2023-10-26 05:07 UTC by JanuarAsprilla

2023-10-28 23:53 UTC, wfercanas requested changes

2023-10-28 23:53 UTC, wfercanas commented on src/januar_asprilla/html-css/assets/css/style.css
No guarde estos archivos directemente en /html-css, pues en las otras PR hemos estado creando una carpeta propia para cada actividad.
Cree también una carpeta para esta tarea.

2023-10-28 23:53 UTC, wfercanas commented on src/januar_asprilla/html-css/index.html
> +    <title>Document</title>
Coloque un título que sea relevante para la tarea

2023-10-28 23:53 UTC, wfercanas commented on src/januar_asprilla/html-css/index.html
> +            pattern="[A-Za-zÁÉÍÓÚáéíóúñÑ\s]+"
No es necesario este pattern, ya con que diga que es type text, se aceptan todos los caracteres que podría usar una persona para crear un nombre por muy raro que sea.

2023-10-28 23:53 UTC, wfercanas commented on src/januar_asprilla/html-css/index.html
> +          <input
En todos los inputs le está haciendo falta el attributo `name`, de lo contrario cuando se haga submit del formulario no se va a saber el `value` a qué corresponde.

2023-10-28 23:53 UTC, wfercanas commented on src/januar_asprilla/html-css/index.html
> +          <span class="terminos-text"
Esto es más un `label` que un `span`. De hecho, un label que podría estar vinculado al `id` del input correspondiente.

2023-10-28 23:53 UTC, wfercanas commented on src/januar_asprilla/html-css/index.html
> +          <li class="gray-icon">
Remueva esta clase y utilice las pseudoclases para seleccionar correctamente los `li` que van con el ícono gris. Si no, toda vez que se ingresen nuevos elementos en esta lista toca venir a mano a agregar las clases.

2023-10-28 23:53 UTC, wfercanas commented on src/januar_asprilla/html-css/assets/css/style.css
> +  display: block;
Esta propiedad sobra, el body es block por defecto.

2023-10-28 23:53 UTC, wfercanas commented on src/januar_asprilla/html-css/assets/css/style.css
> +  align-items: center;
Estas dos propiedades tienen sentido solo si el body fuera display flex, cosa que no se recomienda. Así que deje el body en block y elimine estas dos propiedades.

2023-10-28 23:53 UTC, wfercanas commented on src/januar_asprilla/html-css/assets/css/style.css
> +  min-height: 100vh;
Este min-height también sobra, el documento puede fluir hacia abajo sin problema, hasta donde sea necesario.

2023-10-28 23:53 UTC, wfercanas commented on src/januar_asprilla/html-css/assets/css/style.css
> +  margin-right: 0.3rem;
Estas tres propiedades sobran.

2023-10-28 23:53 UTC, wfercanas commented on src/januar_asprilla/html-css/assets/css/style.css
> +  vertical-align: middle;
Tanto display como vertical-align sobran.

2023-10-28 23:55 UTC, wfercanas requested changes

2023-10-28 23:55 UTC, wfercanas commented on src/januar_asprilla/html-css/assets/css/style.css
> +  margin-top: 50rem;
Este margin está muy exagerado, puede reducirlo para que el texto aparezca debajito del formulación.

2023-10-29 16:09 UTC, JanuarAsprilla commented on src/januar_asprilla/html-css/index.html
> +    <title>Document</title>
listo

2023-10-29 16:10 UTC, JanuarAsprilla commented on src/januar_asprilla/html-css/index.html
> +            pattern="[A-Za-zÁÉÍÓÚáéíóúñÑ\s]+"
listo

2023-10-29 16:12 UTC, JanuarAsprilla commented on src/januar_asprilla/html-css/index.html
> +          <input
listo

2023-10-29 16:13 UTC, JanuarAsprilla commented on src/januar_asprilla/html-css/assets/css/style.css
> +  display: block;
listo

2023-10-29 16:13 UTC, JanuarAsprilla commented on src/januar_asprilla/html-css/assets/css/style.css
> +  align-items: center;
listo

2023-10-29 16:14 UTC, JanuarAsprilla commented on src/januar_asprilla/html-css/assets/css/style.css
> +  min-height: 100vh;
listo

2023-10-29 16:14 UTC, JanuarAsprilla commented on src/januar_asprilla/html-css/assets/css/style.css
> +  margin-right: 0.3rem;
listo

2023-10-29 16:16 UTC, JanuarAsprilla commented on src/januar_asprilla/html-css/assets/css/style.css
> +  margin-top: 50rem;
listo

2023-10-31 20:30 UTC, JanuarAsprilla commented on src/januar_asprilla/html-css/assets/css/style.css
listo

2023-10-31 20:55 UTC, JanuarAsprilla commented on src/januar_asprilla/html-css/index.html
> +          <li class="gray-icon">
listo

2023-11-01 02:36 UTC, JanuarAsprilla commented on src/januar_asprilla/html-css/index.html
> +          <span class="terminos-text"
listo

2023-11-01 16:59 UTC, wfercanas approved these changes

2023-11-01 16:59 UTC, merged