refactor: attending issues
selsa-inube/bootcamp pull request #334
Opened 2023-10-26 18:45 UTC by carin91

i did not delete the link cause this is related to the fb and twitter icons.

2023-10-29 00:42 UTC, wfercanas requested changes

2023-10-29 00:42 UTC, wfercanas commented on src/carin/A3/press-release.html
> +    </div>
Este `div` en realidad debería ser un `nav`. Sin embargo, en la tarea no está incluido hacer esta parte de la página, por lo que puede borrarla.

2023-10-29 00:42 UTC, wfercanas commented on src/carin/A3/press-release.html
> +        </h4>
Aquí está usando un `h4` saltando desde un `h1`. Como esta PR es a partir de una rama nueva, no sé que pudo haber contestado en la PR original.
Sin embargo, esto vienen siendo textos que acompañan al título, por lo que bien podrían ser simples párrafos.

2023-10-29 00:42 UTC, wfercanas commented on src/carin/A3/press-release.html
> +          </span>
Tanto los `span` como los `a` son elementos inline por defecto, por lo tanto los `span` sobrarían si es que su propósito es hacer que los íconos vayan uno al lado del otro.

2023-10-29 00:42 UTC, wfercanas commented on src/carin/A3/press-release.html
> +        <div>
Este div sí podría tener un id o una clase para que aplique los estilos de esta sección de íconos de redes sociales. Faltan detalles como espaciado, text-decoration y :hover para que se parezcan a la página original.

2023-10-29 00:42 UTC, wfercanas commented on src/carin/A3/press-release.html
> +      .div-images {
Esta imagen lleva border-radius.

2023-10-29 00:42 UTC, wfercanas commented on src/carin/A3/press-release.html
> +      <img class="div-images" src="press-release.png" alt="picture1" />
El alt es un texto que se muestra si la imagen no puede cargarse. Según WCAG, es preferible dejar el `alt=""` vacío a poner un texto que no describa la foto.

2023-10-29 00:42 UTC, wfercanas commented on src/carin/A3/press-release.html
> +        </p>
Este texto sirve más como complemento a la foto que está arriba que como inicio de otro bloque. Puede envolver la foto y este texto en un `figure` y reemplazar este `p` por un `figcaption` que vaya despues de la `img`

2023-10-29 00:42 UTC, wfercanas commented on src/carin/A3/press-release.html
> +            <strong>“Ted Lasso”</strong>
Este texto está suelto con respecto a la lista que viene a continuación. En realidad, la lista corresponde a las nominaciones de este texto que está dentro del `strong`

**Sugerencia**: reformule el HTML para que se logre evidenciar que este texto y la lista de abajo son un grupo y no dos cosas separadas.

**Nota**: Aplica para las listas de abajo también.

2023-10-29 00:42 UTC, wfercanas commented on src/carin/A3/press-release.html
> +            <strong>“Home Before Dark”</strong>
Estos textos en `strong` y los párrafos subsiguientes, también pueden quedar mejor agrupados en el documento usando `sections`. De esa manera se identifica que van juntos.

2023-10-29 00:42 UTC, wfercanas commented on src/carin/A3/press-release.html
> +            <span class="col-1">
Aquí también sobran los `span`

2023-10-29 00:42 UTC, wfercanas commented on src/carin/A3/press-release.html
> +      }
Estas reglas con .navbar1 y .navbar2 sobran

2023-10-30 10:36 UTC, carin91 commented on src/carin/A3/press-release.html
> +    </div>
attended
![image](https://github.com/selsa-inube/bootcamp/assets/123512032/f6d68fa7-23f6-4f83-a2c0-724d1a46b9e4)

2023-10-30 10:38 UTC, carin91 commented on src/carin/A3/press-release.html
> +        </h4>
attended 
![image](https://github.com/selsa-inube/bootcamp/assets/123512032/c64e2df5-c8b0-436e-a0e6-cd64ee43a1bf)

2023-10-30 10:40 UTC, carin91 commented on src/carin/A3/press-release.html
> +          </span>
attended -> col-1 was included in a classes
![image](https://github.com/selsa-inube/bootcamp/assets/123512032/476aa9d1-e854-48e3-b9b1-6956a0834d7f)

2023-10-30 10:56 UTC, carin91 commented on src/carin/A3/press-release.html
> +        <div>
applied
![image](https://github.com/selsa-inube/bootcamp/assets/123512032/d9d51ff8-81cb-47a5-8ab8-d841d02d9c56)

2023-10-30 10:57 UTC, carin91 commented on src/carin/A3/press-release.html
> +      .div-images {
applied 
![image](https://github.com/selsa-inube/bootcamp/assets/123512032/3c266eba-9bd3-4089-bfa9-75fabecfdffa)

2023-10-30 11:03 UTC, carin91 commented on src/carin/A3/press-release.html
> +        </p>
attended 
![image](https://github.com/selsa-inube/bootcamp/assets/123512032/4c8660d0-3fc2-4081-9419-173b9cc96d95)

2023-10-30 11:08 UTC, carin91 commented on src/carin/A3/press-release.html
> +            <strong>“Ted Lasso”</strong>
attended
![image](https://github.com/selsa-inube/bootcamp/assets/123512032/7221f19c-c686-47b3-b302-507b08e8d5f3)

2023-10-30 11:11 UTC, carin91 commented on src/carin/A3/press-release.html
> +            <strong>“Home Before Dark”</strong>
attended
![image](https://github.com/selsa-inube/bootcamp/assets/123512032/47a0583c-1a90-497f-b92d-022b02c95f3a)

2023-10-30 11:11 UTC, carin91 commented on src/carin/A3/press-release.html
> +            <span class="col-1">
attended
![image](https://github.com/selsa-inube/bootcamp/assets/123512032/9fc31668-b237-4e02-b2b4-3420c30a7ed7)

2023-10-30 11:13 UTC, carin91 commented on src/carin/A3/press-release.html
> +      }
.navbar1 is not used, so is deleted. .navbar2 is used in nav
![image](https://github.com/selsa-inube/bootcamp/assets/123512032/815b0bef-39fd-4b0b-93b0-b775a847e859)

2023-10-30 20:47 UTC, wfercanas approved these changes

2023-10-30 20:48 UTC, merged