feat: first A5 version
selsa-inube/bootcamp pull request #337
Opened 2023-10-27 15:11 UTC by carin91

2023-10-29 02:06 UTC, wfercanas requested changes

2023-10-29 02:06 UTC, wfercanas commented on src/carin/A5/A5.html
> +            <input
En este `input` falta el atributo `name`

2023-10-29 02:06 UTC, wfercanas commented on src/carin/A5/A5.html
> +            </span>
Los `button` tienen `display: inline` por defecto, este `span` sobra.

2023-10-29 02:06 UTC, wfercanas commented on src/carin/A5/A5.html
> +          <div>
Estos div no están siendo funcionales para organizar el contenido que pueda estar por dentro, sino para resolver un problema de `display: block`.
Puede ser mejor simplificar el documento HTML eliminando estos `div` y resolver el tema de estilos con CSS. Puede hacer uso de `display:inline` con los `input`.

2023-10-29 02:06 UTC, wfercanas commented on src/carin/A5/A5.html
> +            </span>
Este `span` podría convertirse mejor en un `label` y contener tanto el texto como el `input`. Ahora mismo el checkbox está quedando algo desconectado del texto.

2023-10-29 02:06 UTC, wfercanas commented on src/carin/A5/A5.html
> +        <h1>Terms and conditions</h1>
Este sería el tercer `h1`, puede cambiarse.

2023-10-30 11:19 UTC, carin91 commented on src/carin/A5/A5.html
> +      <div class="nav-bar"><h1>Navigation bar</h1></div>
attended 
![image](https://github.com/selsa-inube/bootcamp/assets/123512032/232b5449-3676-49d4-bf6f-f31c3b9165b8)

2023-10-30 11:22 UTC, carin91 commented on src/carin/A5/A5.html
> +      <div class="nav-bar"><h1>Navigation bar</h1></div>
attended
![image](https://github.com/selsa-inube/bootcamp/assets/123512032/f3582e22-294e-4f62-be3c-76fe189ae8a6)

2023-10-30 11:23 UTC, carin91 commented on src/carin/A5/A5.html
> +              name="i-like"
attended
![image](https://github.com/selsa-inube/bootcamp/assets/123512032/5dd9d44e-c6e1-49e8-983d-9e581befe424)

2023-10-30 11:24 UTC, carin91 commented on src/carin/A5/A5.html
> +            <input
attended
![image](https://github.com/selsa-inube/bootcamp/assets/123512032/b9854c44-d34c-4006-b5bc-f471285e4444)

2023-10-30 11:26 UTC, carin91 commented on src/carin/A5/A5.html
> +            </span>
attended 
![image](https://github.com/selsa-inube/bootcamp/assets/123512032/88df52df-99ee-47f4-8dd2-223e36e64079)

2023-10-30 11:33 UTC, carin91 commented on src/carin/A5/A5.html
> +          <div>
attended
![image](https://github.com/selsa-inube/bootcamp/assets/123512032/ab3943bd-14f4-4ffc-88f0-31d61a165d3f)

2023-10-30 11:42 UTC, carin91 commented on src/carin/A5/A5.html
> +            </span>
Attended: span deleted, label included. In label was included the atribute for="checking-terms" to relate this label to the input.
![image](https://github.com/selsa-inube/bootcamp/assets/123512032/a6d795ae-0d89-4f19-82d4-62b1031e4f20)

2023-10-30 11:43 UTC, carin91 commented on src/carin/A5/A5.html
> +        <h1>Terms and conditions</h1>
Refactoring the document: h1 was added and the others were change to h2.
![image](https://github.com/selsa-inube/bootcamp/assets/123512032/5c766a63-e254-4641-b547-5f1b355aa5e2)

2023-10-30 21:02 UTC, wfercanas requested changes

2023-10-30 21:02 UTC, wfercanas commented on src/carin/A5/A5_styles.css
> +.terms-conditions {
Falta resolver el punto de que los términos y condiciones cambien de fondo cuando el usuario navega hacia allí con el `a` del form. Aquí se trata de usar la pseudoclase `:target`

2023-10-30 21:02 UTC, wfercanas commented on src/carin/A5/A5_styles.css
Falta manipular los estilos del `a`, para que se comporte diferente en sus 4 posibles estados (link, visited, hover, active).

2023-10-30 22:20 UTC, carin91 commented on src/carin/A5/A5_styles.css
> +.terms-conditions {
attended

2023-10-30 22:20 UTC, carin91 commented on src/carin/A5/A5_styles.css
attended

2023-10-31 20:15 UTC, wfercanas approved these changes

2023-10-31 20:15 UTC, merged