Ja/6/selectors without classes and ids
selsa-inube/bootcamp pull request #338
Opened 2023-10-27 22:13 UTC by JanuarAsprilla

2023-10-29 02:24 UTC, wfercanas requested changes

2023-10-29 02:24 UTC, wfercanas commented on src/januar_asprilla/html-css/selectors-without-classes-and-ids/index.html
> +        </div>
Este `p` puede ir sólo, no necesita del `div` que lo envuelve. Me refiero al `p` que dice "Asimismo, el estudio..."

2023-10-29 02:24 UTC, wfercanas commented on src/januar_asprilla/html-css/selectors-without-classes-and-ids/index.html
> +        <div>
Este `div` se puede reemplazar por un `article`. Esto permite que en los estilos sea más fácil identicar las reglas que le están aplicando a estas cajas que tienen estos números grandes y que a veces ocupan todo el ancho y a veces ocupan sólo la mitad.

2023-10-29 02:24 UTC, wfercanas commented on src/januar_asprilla/html-css/selectors-without-classes-and-ids/index.html
> +        </div>
Este `div` también sobra. Particularmente revise todos aquellos div donde sólo está guardando un `p` por dentro. Todos ellos son candidatos a ser eliminados.

2023-10-29 02:24 UTC, wfercanas commented on src/januar_asprilla/html-css/selectors-without-classes-and-ids/index.html
> +          <div>
Este div sobra, la lista `ul` puede hacerse cargo sola.

2023-10-29 16:25 UTC, JanuarAsprilla commented on src/januar_asprilla/html-css/selectors-without-classes-and-ids/index.html
> +        </div>
listo

2023-10-29 16:25 UTC, JanuarAsprilla commented on src/januar_asprilla/html-css/selectors-without-classes-and-ids/index.html
> +        <div>
listo

2023-10-29 16:26 UTC, JanuarAsprilla commented on src/januar_asprilla/html-css/selectors-without-classes-and-ids/index.html
> +        </div>
listo

2023-11-01 02:39 UTC, wfercanas approved these changes

2023-11-01 02:39 UTC, merged