feat: new A6 document
selsa-inube/bootcamp pull request #341
Opened 2023-10-30 15:20 UTC by carin91

2023-10-30 21:38 UTC, wfercanas requested changes

2023-10-30 21:38 UTC, wfercanas commented on src/carin/A6/index-A6.html
> +            </table>
Es preferible no usar tablas para generar layouts. Le sugiero un par de cambios.
1. Los articles suelen usarse tanto para artículos completos cuando en una página hay varios de ellos, o para elementos reutilizables dentro de un único texto (como es este el caso). Entonces, en lugar de usar el `article` para todo el texto, úselo para estas tarjetas.
2. En lugar del `article` global que está usando, puede implementar un `main`

Le comparto documentación sobre este uso alternativo del `article`:  https://developer.mozilla.org/en-US/docs/Web/HTML/Element/article

2023-10-30 21:38 UTC, wfercanas commented on src/carin/A6/index-A6.html
> +          <table>
Si refactorizó arriba para usar un article y no recurrir a una tabla, aquí puede tener el reto de ubicar ambas cajas una al lado de la otra.
Intente usar el display:inline-block para que pueda definir el ancho de cada caja sin perder el hecho de que pueda ir una al lado de la otra.

De hecho así puede controlar que se esté usando todo el ancho y no sólo un pedazo a la izquierda.

2023-10-30 21:38 UTC, wfercanas commented on src/carin/A6/styles-A6.css
> +  padding-left: 5%;
Puede mejorar el uso del padding o margin para que la caja quede realmente flotando y distanciada del resto del texto.

2023-10-30 22:38 UTC, carin91 commented on src/carin/A6/index-A6.html
> +            </table>
attended 
![image](https://github.com/selsa-inube/bootcamp/assets/123512032/101a4fa2-7c53-47ea-a4cb-126a028e1ef4)

2023-10-30 22:39 UTC, carin91 commented on src/carin/A6/index-A6.html
> +          <table>
attended 
![image](https://github.com/selsa-inube/bootcamp/assets/123512032/fedd4034-d005-4f08-b517-1a9a7424fbf8)

2023-10-30 23:10 UTC, carin91 commented on src/carin/A6/styles-A6.css
> +  padding-left: 5%;
attended. padding 5%;, all of this span contents are responsive now.

2023-10-31 20:22 UTC, wfercanas approved these changes

2023-10-31 20:25 UTC, merged