cr/9/A9
selsa-inube/bootcamp pull request #342
Opened 2023-10-31 10:59 UTC by carin91

2023-11-01 02:26 UTC, wfercanas requested changes

2023-11-01 02:26 UTC, wfercanas commented on src/carin/A9/styles-A9.css
> +  float: left;
Es suficiente con el `float: left` de la barra de navegación.

2023-11-01 02:26 UTC, wfercanas commented on src/carin/A9/styles-A9.css
> +sidebar {
Es importante definir el ancho de esta barra de navegación para que de esa manera se genere el espacio vacío al lado derecho y que de esa forma se pueda ubicar ahí el resto del contenido.

2023-11-01 02:26 UTC, wfercanas commented on src/carin/A9/styles-A9.css
> +  margin-left: 5vw;
Estos margin tan fuertes le pueden causar problemas. Quizá ya dentro de la sección principal de la app pueda usar `flex` así como lo usó en el nav para organizar los elementos y no recurrir a estos margin tan grandes.

2023-11-02 07:53 UTC, carin91 commented on src/carin/A9/index-A9.html
> +          Ikako Talavadze
attended
![image](https://github.com/selsa-inube/bootcamp/assets/123512032/e674ce16-26b2-43ce-b9bc-f73bc7fe0fc8)

2023-11-02 08:01 UTC, carin91 commented on src/carin/A9/index-A9.html
> +        <hr />
attended
![image](https://github.com/selsa-inube/bootcamp/assets/123512032/97926e9e-09a2-45b3-88d2-50de44389ab1)

2023-11-02 08:05 UTC, carin91 commented on src/carin/A9/index-A9.html
> +        </nav>
attended, i also included a ul selector for list without bullets.

![image](https://github.com/selsa-inube/bootcamp/assets/123512032/de62d42d-6b76-46e3-8c4f-3cf2f11c1634)

2023-11-02 08:17 UTC, carin91 commented on src/carin/A9/styles-A9.css
attended 
![image](https://github.com/selsa-inube/bootcamp/assets/123512032/1e623ba3-5e33-4286-b863-9591b26266ff)

2023-11-02 08:18 UTC, carin91 commented on src/carin/A9/styles-A9.css
attended 
![image](https://github.com/selsa-inube/bootcamp/assets/123512032/15395e53-5271-4933-ae1b-263a2d55e65d)

2023-11-02 08:21 UTC, carin91 commented on src/carin/A9/index-A9.html
> +      <sidebar>
attended
![image](https://github.com/selsa-inube/bootcamp/assets/123512032/9e5487ad-8bb3-456c-b00c-946eb4528462)

2023-11-02 08:27 UTC, carin91 commented on src/carin/A9/index-A9.html
> +      <content>
attended
![image](https://github.com/selsa-inube/bootcamp/assets/123512032/6eb65644-c633-4d4d-b7d9-c0583d4d2d59)

2023-11-02 08:30 UTC, carin91 commented on src/carin/A9/styles-A9.css
> +  float: left;
not attended:
I assinged float: left; for both elements to place them one after another, if a delete this line it does not work.
![image](https://github.com/selsa-inube/bootcamp/assets/123512032/079cfd96-322c-4cb3-8a66-55f74983accb)

2023-11-02 08:32 UTC, carin91 commented on src/carin/A9/styles-A9.css
> +sidebar {
attended 
![image](https://github.com/selsa-inube/bootcamp/assets/123512032/d4a94bf6-c761-4489-bb6e-dda9a772450e)

2023-11-02 08:50 UTC, carin91 commented on src/carin/A9/styles-A9.css
> +  float: left;
attended

2023-11-02 09:02 UTC, carin91 commented on src/carin/A9/styles-A9.css
> +  margin-left: 5vw;
attended
![image](https://github.com/selsa-inube/bootcamp/assets/123512032/bb99dda5-4299-45ed-9cc9-dd3150c31bbc)

2023-11-03 14:36 UTC, wfercanas approved these changes

2023-11-03 14:36 UTC, merged