lo/17/sidebar
selsa-inube/bootcamp pull request #343
Opened 2023-11-02 05:36 UTC by LinconOssa

2023-11-03 15:12 UTC, wfercanas requested changes

2023-11-03 15:12 UTC, wfercanas commented on src/Lincon/html-css/17-Sidebar/index.html
> +          <div id="logo">
Este `div` se puede eliminar, sólo contiene la imagen. De hecho, de todos los estilos de #logo, casi que todos menos el `margin-top` se pueden obviar.

2023-11-03 15:12 UTC, wfercanas commented on src/Lincon/html-css/17-Sidebar/index.html
> +                ⋮⋮<img src="ima/mercedes.png" alt="mercedes" />
Refactorice para que esos puntos, que son estéticos y no contenido, se apliquen usando CSS y no HTML.
Puede usar el pseudoelemento `::before`

2023-11-03 15:12 UTC, wfercanas commented on src/Lincon/html-css/17-Sidebar/styles.css
A nivel de estilos en general está bien, pero hace falta mejorar el uso del espacio vertical de la barra.
Actualmente no está usando todo el alto de la pantalla para la barra, como sí está en la imagen de referencia.

Consideraciones:
1. El avatar del usuario debería aparecer en la parte inferior de la pantall.
2. Los dos íconos que van arriba del avatar deberían mantener la misma distancia siempre con respecto al avatar (si el avatar se baja, ellos también).
3. Si la barra se alarga hacia abajo, el espacio blanco que se crea quedaría entre el botón de Add New Project y el grupo del avatar y sus dos íconos acompañantes.

2023-11-03 19:34 UTC, LinconOssa commented on src/Lincon/html-css/17-Sidebar/index.html
> +          <div id="logo">
Listo

2023-11-03 19:34 UTC, LinconOssa commented on src/Lincon/html-css/17-Sidebar/index.html
> +                ⋮⋮<img src="ima/mercedes.png" alt="mercedes" />
Listo

2023-11-03 19:37 UTC, LinconOssa commented on src/Lincon/html-css/17-Sidebar/styles.css
Listo.

2023-11-08 18:01 UTC, wfercanas approved these changes

2023-11-08 18:01 UTC, merged