feat: new cr/17/A17
selsa-inube/bootcamp pull request #350
Opened 2023-11-07 18:31 UTC by carin91

2023-11-08 20:55 UTC, wfercanas requested changes

2023-11-08 20:55 UTC, wfercanas commented on src/carin/A17/index-A17.html
> +            <li id="active-plan" class="dropdown">
Esta lista `ul` sólo contiene un elemento `li`. No tiene mucho sentido una lista de un sólo elemento. Podrían eliminarse ambos elementos y dejar sólo un `div`.

2023-11-08 20:55 UTC, wfercanas commented on src/carin/A17/index-A17.html
> +                  <div class="plan">
Este `div` sólo contiene a la imagen y tiene una clase que sólo es usada por este `div`. Podría eliminar este div y trabajar directamente con la imagen.

2023-11-08 20:55 UTC, wfercanas commented on src/carin/A17/styles-A17.css
Evalúe el uso que pueda estar haciendo de las propiedades del box-model de los elementos, pues varios de ellos se están saliendo de las áreas demarcadas para ellos.

![image](https://github.com/selsa-inube/bootcamp/assets/36939686/1e1b4022-9c4d-48fc-88fd-ed7a1eafdefa)

2023-11-08 20:55 UTC, wfercanas commented on src/carin/A17/styles-A17.css
El `hover` sobre algunos elementos de la lista no está quedando simétrico. Se activa un área importante pero sólo hacia abajo del ícono, lo que hace que no se vea agradable el efecto.

**Nota**: yo le cambié el color al background a verde para poder tomar este pantallazo y que se viera bien a lo que me refiero.

![image](https://github.com/selsa-inube/bootcamp/assets/36939686/1415b1b5-e1de-4ac5-a7c7-32d24301431b)

2023-11-08 20:55 UTC, wfercanas commented on src/carin/A17/index-A17.html
> +              <a href="#"><i class="fa fa-search" aria-hidden="true"></i></a>
Hace falta resolver un aparte del ejercicio y es que al hacer hover sobre los íconos, estos muestren el título de la opción en una especie de tooltip.

Averigüe sobre la etiqueta `<abbr>`

2023-11-08 20:55 UTC, wfercanas commented on src/carin/A17/index-A17.html
> +        <nav class="nav-shared">
Para cada `div` de estos principales, sólo hay un `nav` por dentro. Serían 6 div, con sólo 6 `nav` como hijos directos. Si en realidad todo el sidebar son elementos `nav`, es mejor que la barra `div.sidebar` sea en realidad un único `nav` y eliminamos así todos los `nav` están por dentro de esos 6 `div`.

1. Con esto minimizamos un anidamiento que podría ser innecesario.
2. De hecho, hasta los mismos `div` podrían también eliminarse y dejar directamente las listas `ul`, pues tampoco tiene sentido dejar un `div` para envolver sólo una lista.

2023-11-08 20:55 UTC, wfercanas commented on src/carin/A17/index-A17.html
> +              <a href="#"><button class="project-new">+</button> </a>
El border de estos buttons se puede mejorar para que se parezcan más a los del mockup

2023-11-08 20:55 UTC, wfercanas commented on src/carin/A17/index-A17.html
> +      <hr />
Los estilos de este divisor se pueden mejorar para que se parezca más al mockup

2023-11-08 20:55 UTC, wfercanas commented on src/carin/A17/index-A17.html
> +            <li class="dropdown">
Esta lista con este `li` también se pueden eliminar y reemplazarlos por un `div`. Esto porque igual que arriba, una lista de un sólo elemento no tiene mucho sentido en este caso.

2023-11-08 20:55 UTC, wfercanas commented on src/carin/A17/styles-A17.css
Falta que el documento tenga un alto de 200vh y poder identificar que aún con el scroll el sidebar sigue fijo a la izquierda.

2023-11-08 20:55 UTC, wfercanas commented on src/carin/A17/styles-A17.css
El movimiento del cursor entre el sidebar y los menús que se abren al hacer hover tiene que ser rápido para que el menú no se desaparezca en el proceso.

Evaluar alguna estrategia para que el usuario no tenga que mover el mouse a alta velocidad, sino que lo pueda hacer despacio y no perder el menú emergente.

2023-11-08 20:55 UTC, wfercanas commented on src/carin/A17/styles-A17.css
El sidebar no está distribuyendo el espacio vertical de forma tal que use todo el alto de la pantalla. Si la pantalla es alta, de todas formas el menú del usuario debe permanecer en la parte inferior de la sidebar, no subirse.

![image](https://github.com/selsa-inube/bootcamp/assets/36939686/f52118ee-8d3a-46af-95e0-7a79fa795190)

2023-11-09 12:19 UTC, carin91 commented on src/carin/A17/index-A17.html
> +              <a href="#"><i class="fa fa-search" aria-hidden="true"></i></a>
Attended, i cannot find a way to change title styles, a person in stackoverflow stands that it cannot be change and depends on the user's OS. https://stackoverflow.com/questions/17472440/styling-html-title-attribute-using-css


![image](https://github.com/selsa-inube/bootcamp/assets/123512032/f9b02284-48ca-4f61-99bf-e0cb7a5ed16c)

2023-11-09 12:29 UTC, carin91 commented on src/carin/A17/index-A17.html
> +        <nav class="nav-shared">
attended
![image](https://github.com/selsa-inube/bootcamp/assets/123512032/9106484b-40a9-4fc0-8bfd-155776197c55)

2023-11-09 12:30 UTC, carin91 commented on src/carin/A17/index-A17.html
> +            <li id="active-plan" class="dropdown">
![image](https://github.com/selsa-inube/bootcamp/assets/123512032/af554fd8-84a9-4f40-8d46-79d2cdaaa321)
attended

2023-11-09 12:32 UTC, carin91 commented on src/carin/A17/index-A17.html
> +              <a href="#"><button class="project-new">+</button> </a>
attended
![image](https://github.com/selsa-inube/bootcamp/assets/123512032/df62a025-9312-4f7d-ac92-088c45b871c3)

2023-11-09 12:35 UTC, carin91 commented on src/carin/A17/index-A17.html
> +      <hr />
attended with color change
![Uploading image.png…]()

2023-11-09 12:36 UTC, carin91 commented on src/carin/A17/index-A17.html
> +            <li class="dropdown">
attended
![image](https://github.com/selsa-inube/bootcamp/assets/123512032/a32ba5aa-0fa1-4c8f-8ede-56dd62358801)

2023-11-09 12:38 UTC, carin91 commented on src/carin/A17/styles-A17.css
attended
![image](https://github.com/selsa-inube/bootcamp/assets/123512032/e5498c72-8650-4d66-8416-bd920a636cc0)
![image](https://github.com/selsa-inube/bootcamp/assets/123512032/d2b982ea-2da9-4e8c-9362-a84746c3c937)

2023-11-09 13:35 UTC, carin91 commented on src/carin/A17/styles-A17.css
attended:

Added flex properties to nav

2023-11-09 13:45 UTC, carin91 commented on src/carin/A17/styles-A17.css
attended
![image](https://github.com/selsa-inube/bootcamp/assets/123512032/d9713224-0090-4d41-8180-81405244357b)

2023-11-09 13:46 UTC, carin91 commented on src/carin/A17/styles-A17.css
attended
![image](https://github.com/selsa-inube/bootcamp/assets/123512032/91fded17-e863-4ac3-a6aa-864ab907b3b3)

2023-11-09 14:11 UTC, carin91 commented on src/carin/A17/styles-A17.css
attended
![image](https://github.com/selsa-inube/bootcamp/assets/123512032/8b3038a3-7873-45dc-9402-c3fdc6b00b81)

2023-11-09 14:14 UTC, carin91 commented on src/carin/A17/index-A17.html
> +                  <div class="plan">
attended
![image](https://github.com/selsa-inube/bootcamp/assets/123512032/3941590e-9dcd-44da-8c9a-45cb3f09b747)

2023-11-09 16:34 UTC, wfercanas approved these changes

2023-11-09 16:34 UTC, merged