Ja/22/landing  page
selsa-inube/bootcamp pull request #351
Opened 2023-11-08 17:32 UTC by JanuarAsprilla

2023-11-23 22:21 UTC, wfercanas requested changes

2023-11-23 22:21 UTC, wfercanas commented on src/januar_asprilla/html-css/landing-page/index.html
> +    <header>
El media query de este `header` podría mejorarse, pues se está rompiendo y sólo hasta un tamaño casi mobile se hace el ajuste. Puede aplicar el mobile mucho antes, evitando que se rompa el `header`.

2023-11-23 22:21 UTC, wfercanas commented on src/januar_asprilla/html-css/landing-page/index.html
> +        </div>
El `div` sobra, puede usar directamente el `i`

2023-11-23 22:21 UTC, wfercanas commented on src/januar_asprilla/html-css/landing-page/index.html
> +          <li>Discover</li>
Si es una lista de navegación, adentro tendría que ir un `a` así sea con un `href` ficticio.

2023-11-23 22:21 UTC, wfercanas commented on src/januar_asprilla/html-css/landing-page/index.html
> +        </div>
En vez de un `div` y un `p`, es suficiente sólo con un `button`

2023-11-23 22:21 UTC, wfercanas commented on src/januar_asprilla/html-css/landing-page/index.html
> +          <div id="botones-extra-info">
No use `div` para botones, use directamente los `button`

2023-11-23 22:21 UTC, wfercanas commented on src/januar_asprilla/html-css/landing-page/index.html
> +          <div id="botones-extra-info">
Los botones se están rompiendo en tamaños aún grandes. Está quedando el texto a dos renglones.
Puede de hecho aplicar el responsive de forma anticipada para que la transición entre un layout y otro sea más suave, no tan de golpe.

2023-11-23 22:21 UTC, wfercanas commented on src/januar_asprilla/html-css/landing-page/index.html
La imagen en el fondo tiene una parte negra y otra blanca, la imagen principal no está toda sobre fondo negro.

2023-11-24 10:58 UTC, JanuarAsprilla commented on src/januar_asprilla/html-css/landing-page/index.html
> +        </div>
corregido

2023-11-24 11:01 UTC, JanuarAsprilla commented on src/januar_asprilla/html-css/landing-page/index.html
> +          <li>Discover</li>
corregido

2023-11-24 11:04 UTC, JanuarAsprilla commented on src/januar_asprilla/html-css/landing-page/index.html
> +        </div>
corregido

2023-11-24 11:14 UTC, JanuarAsprilla commented on src/januar_asprilla/html-css/landing-page/index.html
listo

2023-11-24 11:40 UTC, JanuarAsprilla commented on src/januar_asprilla/html-css/landing-page/index.html
> +          <div id="botones-extra-info">
corregido

2023-11-24 11:40 UTC, JanuarAsprilla commented on src/januar_asprilla/html-css/landing-page/index.html
> +          <div id="botones-extra-info">
corregido

2023-11-28 14:51 UTC, wfercanas approved these changes

2023-11-28 14:51 UTC, merged