lo/22/landing page
selsa-inube/bootcamp pull request #352
Opened 2023-11-08 21:40 UTC by LinconOssa

2023-11-23 22:26 UTC, wfercanas requested changes

2023-11-23 22:26 UTC, wfercanas commented on src/Lincon/html-css/22-Landing Page/index.html
> +    <article>
Cuando está aplicando el responsive mobile, están quedando estos textos alineados a la izquierda.
Puede aplicar un max-width y hacer que los textos sigan centrados junto con la imagen y no todo a la izquierda.

2023-11-25 03:13 UTC, LinconOssa commented on src/Lincon/html-css/22-Landing Page/index.html
> +    <article>
Listo

2023-11-26 16:50 UTC, wfercanas approved these changes

2023-11-26 16:50 UTC, merged