Lo/23/stella studio
selsa-inube/bootcamp pull request #355
Opened 2023-11-09 19:59 UTC by LinconOssa

2023-11-24 18:44 UTC, wfercanas requested changes

2023-11-24 18:44 UTC, wfercanas commented on src/Lincon/html-css/23-stella-studio/index.html
Creo que puede bajarle un poquito el tamaño a los headings, para que no se vea tan grande todo el contenido.

2023-11-24 18:44 UTC, wfercanas commented on src/Lincon/html-css/23-stella-studio/index.html
> +        </h1>
Este texto está ocupando todo el ancho de la pantalla. Podría mejorar la estética si tuviera un max-width para que no se vea además de grande, invasivo al usar todo el ancho.

2023-11-25 04:57 UTC, LinconOssa commented on src/Lincon/html-css/23-stella-studio/index.html
listo

2023-11-25 04:57 UTC, LinconOssa commented on src/Lincon/html-css/23-stella-studio/index.html
> +        </h1>
listo

2023-11-26 16:55 UTC, wfercanas commented on src/Lincon/html-css/23-stella-studio/index.html
Se sigue viendo todo muy grande. Mi pantalla es grande y aún así no cabe todo. Le sugiero usar 64px para los h1 y 56px para los h2.
![image](https://github.com/selsa-inube/bootcamp/assets/36939686/4762c531-6d95-4035-9508-4b08b1b99702)

2023-11-26 17:32 UTC, LinconOssa commented on src/Lincon/html-css/23-stella-studio/index.html
![image](https://github.com/selsa-inube/bootcamp/assets/103295353/f2079367-0515-41a8-bb4f-3301534ede81)
![image](https://github.com/selsa-inube/bootcamp/assets/103295353/4627ce65-a1de-42b7-b032-f1dda2b2614e)
Cambio listo

2023-11-27 15:16 UTC, wfercanas approved these changes

2023-11-27 15:17 UTC, merged