Ja/23/stella studio
selsa-inube/bootcamp pull request #356
Opened 2023-11-10 06:03 UTC by JanuarAsprilla

2023-11-24 18:38 UTC, wfercanas requested changes

2023-11-24 18:38 UTC, wfercanas commented on src/januar_asprilla/html-css/stella-studio/index.html
> +            <p>Get Outle</p>
Es preferible que estos `p` sean más bien unos `button`

2023-11-24 18:38 UTC, wfercanas commented on src/januar_asprilla/html-css/stella-studio/index.html
> +      <section>
Esta sección no tiene el layout del dibujo. Está apareciendo el título a la izquierda y la imagen a la derecha y abajo. Se trata de reacomodar las piezas.

2023-11-24 18:38 UTC, wfercanas commented on src/januar_asprilla/html-css/stella-studio/index.html
> +      <section>
El fondo oscuro de esta sección debe ocupar todo el ancho de la pantalla, no sólo la parte central. Están quendando los márgenes izquierdo y derecho en blanco.

2023-11-26 19:29 UTC, JanuarAsprilla commented on src/januar_asprilla/html-css/stella-studio/index.html
> +      <header>
corregido

2023-11-26 19:36 UTC, JanuarAsprilla commented on src/januar_asprilla/html-css/stella-studio/index.html
> +            <p>Get Outle</p>
corregido, acción realizada en todos los botones

2023-11-26 20:00 UTC, JanuarAsprilla commented on src/januar_asprilla/html-css/stella-studio/index.html
> +      <section>
corregido

2023-11-28 15:11 UTC, wfercanas requested changes

2023-11-28 16:12 UTC, JanuarAsprilla commented on src/januar_asprilla/html-css/stella-studio/index.html
> +      <section>
corregido

2023-11-29 15:40 UTC, wfercanas approved these changes

2023-11-29 15:40 UTC, merged