cr/22/Landing Page
selsa-inube/bootcamp pull request #357
Opened 2023-11-10 13:30 UTC by carin91

2023-11-23 22:40 UTC, wfercanas requested changes

2023-11-23 22:40 UTC, wfercanas commented on src/carin/A22/index-a22.html
> +    <header>
Los textos del header están con un tamaño dinámico, haciendo que en ocasiones tenga un tamaño de 8px que es difícil de leer y en otros breakpoints tenga un tamaño de 28-30px, que ya es muy grande.

Generalmente los textos no tienen tamaños dependientes del viewport, sino que manejan tamaños fijos. Estos sí pueden cambiar de un 16px a un 14px dentro del rango mobile, pero son saltos discretos, no continuos.

**Nota**: Aplica para varios textos dentro del entregable.

2023-11-23 22:40 UTC, wfercanas commented on src/carin/A22/index-a22.html
> +        <p id="intro">Introducing the latest innovation</p>
Los estilos de este texto no coinciden con el mockup. El texto es más pequeño en el mockup y va en un color gris. Tampoco hay tanto espacio entre este texto y el que le sigue debajo.

2023-11-23 22:40 UTC, wfercanas commented on src/carin/A22/index-a22.html
> +        </p>
Este texto tiene un interlineado que es mayor al que está en el mockup.

2023-11-23 22:40 UTC, wfercanas commented on src/carin/A22/index-a22.html
> +      <picture>
La imagen va con los bordes redondeados.

2023-11-27 17:41 UTC, carin91 commented on src/carin/A22/index-a22.html
> +    <header>
attended. Several changes in font-size.

2023-11-27 17:43 UTC, carin91 commented on src/carin/A22/index-a22.html
> +        <p id="intro">Introducing the latest innovation</p>
attended.

2023-11-27 17:44 UTC, carin91 commented on src/carin/A22/index-a22.html
> +        <p id="intro">Introducing the latest innovation</p>
![image](https://github.com/selsa-inube/bootcamp/assets/123512032/cfeb56ff-1199-4851-b423-715929d9486e)

2023-11-27 17:44 UTC, carin91 commented on src/carin/A22/index-a22.html
> +        </p>
attended. Change the line-height to 1.5em

2023-11-27 17:46 UTC, carin91 commented on src/carin/A22/index-a22.html
> +      <picture>
attended
![image](https://github.com/selsa-inube/bootcamp/assets/123512032/33d4c9b6-8b67-40ed-9ea1-80cbda83240d)

2023-11-28 15:00 UTC, wfercanas commented on src/carin/A22/index-a22.html
> +      <picture>
La imagen en desktop está quedando con parte de fondo negro y parte de fondo blanco como debería, pero a medida que se progresa hacia mobile deja de ser así. Esto no debería ocurrir.
![image](https://github.com/selsa-inube/bootcamp/assets/36939686/3c429c2e-b03d-47d8-9f10-f85c42e247fc)

2023-11-28 15:01 UTC, wfercanas commented on src/carin/A22/index-a22.html
> +      </section>
Esta sección se está desbordando en el rango mobile:
![image](https://github.com/selsa-inube/bootcamp/assets/36939686/339b7f6a-6c1d-4521-9d57-de1a03ae39e8)

2023-11-29 11:27 UTC, carin91 commented on src/carin/A22/index-a22.html
> +    <header>
Attended
To avoid this effect i change the max-width rule to 700px, because in 688 the header starts to break the responsive.

![image](https://github.com/selsa-inube/bootcamp/assets/123512032/bcbc1325-9d53-423a-afa4-73c13321cab0)

2023-11-29 12:01 UTC, carin91 commented on src/carin/A22/index-a22.html
> +      </section>
attended

With the other changes the general behavior of the page was adjusted.

2023-11-29 15:36 UTC, wfercanas approved these changes

2023-11-29 15:37 UTC, merged