Ja/27/google
selsa-inube/bootcamp pull request #465
Opened 2023-11-12 06:54 UTC by JanuarAsprilla

2023-11-26 17:11 UTC, wfercanas requested changes

2023-11-26 17:11 UTC, wfercanas commented on src/januar_asprilla/html-css/google/index.html
> +      </figure>
Esta figura se está desbordando y ocupa parte del área del search:
![image](https://github.com/selsa-inube/bootcamp/assets/36939686/f287f58c-a4bf-44ad-8d0a-834a9940802b)

2023-11-26 17:11 UTC, wfercanas commented on src/januar_asprilla/html-css/google/index.html
> +      <form action="Buscar">
Este formulario lo está ubicando usando la propiedad position, por lo que no tiene mucho sentido que use margin. El margin va a pasar por encima del resto de componentes y no va a tener efecto.

Refactorice para que no el formulario no necesite usar position ni translateY. El formulario debería seguir el flujo del documento como cualquier otro elemento.

2023-11-26 17:11 UTC, wfercanas commented on src/januar_asprilla/html-css/google/index.html
> +      <form action="Buscar">
Los elementos que van dentro del formulario los organizó usando `position: absolute`. Eso hace que ellos estén flotando por encima del componente. Refactorice para que el esos elementos no se ubiquen usando position, sino a través de algún layout que defina el formulario.

Sugerencia: puede usar `display: grid` en el form para organizar cada elemento.

Por flotar los elementos, ocurre esto:
![image](https://github.com/selsa-inube/bootcamp/assets/36939686/47a205a3-ed19-4a23-805b-8a21971f2258)

2023-11-26 17:11 UTC, wfercanas commented on src/januar_asprilla/html-css/google/index.html
> +        <button>Voy a tener suerte</button>
Cuando se hace hover sobre estos botones, las dimensiones de los botones cambian y se nota un cambio en la pantalla.
Le sugiero que los botones siempre tengan border, pero que el border sólo se coloree cuando hay hover, de esa manera es sólo un cambio de color y no un cambio en las dimensiones que haga que parezca que los botones se mueven.

2023-11-26 17:11 UTC, wfercanas commented on src/januar_asprilla/html-css/google/index.html
> +      <div class="info-extra">
Le sugiero que este `div` tenga `flex-wrap: wrap` para que mejore el responsive. Sirve inclusive colocar un gap para que no se peguen las listas.

2023-11-26 17:11 UTC, wfercanas commented on src/januar_asprilla/html-css/google/index.html
> +        <div id="info-izquierda">
Este `div` sólo contiene una lista `ul`. Puede quitar el `div` y usar directamente la lista.
Aplica también para el `div` de **info-derecha**.

2023-11-26 20:11 UTC, JanuarAsprilla commented on src/januar_asprilla/html-css/google/index.html
> +      </figure>
corregido

2023-11-26 20:15 UTC, JanuarAsprilla commented on src/januar_asprilla/html-css/google/index.html
> +      <form action="Buscar">
corregido

2023-11-26 21:13 UTC, JanuarAsprilla commented on src/januar_asprilla/html-css/google/index.html
> +        <button>Voy a tener suerte</button>
corregido

2023-11-26 21:17 UTC, JanuarAsprilla commented on src/januar_asprilla/html-css/google/index.html
> +      <div class="info-extra">
corregido

2023-11-28 15:13 UTC, wfercanas approved these changes

2023-11-28 15:13 UTC, merged