cr/1/A1 js
selsa-inube/bootcamp pull request #466
Opened 2023-11-13 18:56 UTC by carin91

2023-11-24 00:42 UTC, wfercanas requested changes

2023-11-24 00:42 UTC, wfercanas commented on src/carin/JS/A1/A1.js
> +  if (a % 3 == 0 && a % 5 == 0) {
Está haciendo cada evaluación dos veces: `a % 3` y `a % 5`. Refactorice para que sólo sea necesaria una evaluación de cada caso.

2023-11-24 00:42 UTC, wfercanas commented on src/carin/JS/A1/A1.js
> +//Chessboard
Refactorice el ejercicio con variables cuyo nombre indiquen para qué es la variable.

2023-11-24 00:42 UTC, wfercanas commented on src/carin/JS/A1/A1.js
> +var a = 1;
Como está usando `var`, javascript le permite redeclarar la misma variable. Sin embargo, es buena práctica evitar esta funcionalidad, pues puede dificultar la lectura y hacer más difícil hacer debug.

2023-11-24 00:42 UTC, wfercanas commented on src/carin/JS/A1/A1.js
> +    console.log(b);
Según el enunciado del ejercicio, todo el chessboard se arma con un único string y ese único string ha de pasarse al console.log. Refactorice para cumplir con esa restricción.

2023-11-24 00:42 UTC, wfercanas commented on src/carin/JS/A1/A1.js
> +  }
En esta secuencia está asignando espacios y numerales siempre de forma alternada hasta cubrir el total de casillas, pero ese escenario sólo funciona en situaciones donde el tablero es impar:

```js
// 3x3
# # // Termina con numeral
 #   // Inicia con espacio -> Termina con espacio
# # // Inicia con numeral
```
Si ahora el tablero es par en sus dimensiones, la secuencia de caracteres ya no es siempre alterna:
```js
// 4x4
# #    // Termina con espacio
 # #   // Inicia con espacio -> Termina con numeral
# #    // Inicia con numeral
 # #
```

2023-11-24 19:07 UTC, carin91 commented on src/carin/JS/A1/A1.js
> +  if (a % 3 == 0 && a % 5 == 0) {
attended 
![Uploading image.png…]()

2023-11-24 19:22 UTC, carin91 commented on src/carin/JS/A1/A1.js
> +//Chessboard
attended
![Uploading image.png…]()

2023-11-24 19:23 UTC, carin91 commented on src/carin/JS/A1/A1.js
> +var a = 1;
attended
![image](https://github.com/selsa-inube/bootcamp/assets/123512032/ff5565a4-299c-4a1a-a5b6-4d4c89064003)

2023-11-24 19:23 UTC, carin91 commented on src/carin/JS/A1/A1.js
> +    console.log(b);
attended
![image](https://github.com/selsa-inube/bootcamp/assets/123512032/008ff95c-a676-46c4-b308-eadbec380a99)

2023-11-24 19:24 UTC, carin91 commented on src/carin/JS/A1/A1.js
> +  }
attended
![image](https://github.com/selsa-inube/bootcamp/assets/123512032/71343e60-0b8b-4507-a773-20a64490d510)

2023-11-26 15:57 UTC, wfercanas approved these changes

2023-11-26 15:57 UTC, merged