lo/29/Netflix
selsa-inube/bootcamp pull request #469
Opened 2023-11-16 02:09 UTC by LinconOssa

2023-12-01 22:24 UTC, wfercanas requested changes

2023-12-01 22:24 UTC, wfercanas commented on src/Lincon/html-css/29-Netflix/index.html
> +        <div class="padre-botones">
Este div `padre-botones` no le encuentro la necesidad. No tiene estilos y sólo contiene un hijo.

2023-12-01 22:24 UTC, wfercanas commented on src/Lincon/html-css/29-Netflix/index.html
> +          <div class="imagenes-overflow">
Este div tiene más caracter de lista `ul`. Cada imagen puede ir dentro de un `li`

2023-12-01 22:24 UTC, wfercanas commented on src/Lincon/html-css/29-Netflix/index.html
> +            <img src="ima/1.jpg" alt="imagenes-overflow" />
El ancho de las imagenes no corresponde con el ancho real al final:
![image](https://github.com/selsa-inube/bootcamp/assets/36939686/552ae617-7fb1-478c-a981-aaebbeb1381d)

2023-12-01 23:07 UTC, LinconOssa commented on src/Lincon/html-css/29-Netflix/index.html
> +        <div class="padre-botones">
Listo eliminado

2023-12-01 23:07 UTC, LinconOssa commented on src/Lincon/html-css/29-Netflix/index.html
> +          <div class="imagenes-overflow">
![image](https://github.com/selsa-inube/bootcamp/assets/103295353/b9ede7d0-bf29-4c29-bea2-8ce5b3508026)
Cambio realizado

2023-12-04 21:46 UTC, wfercanas approved these changes

2023-12-04 21:46 UTC, merged