Ja/29/netflix
selsa-inube/bootcamp pull request #470
Opened 2023-11-17 03:15 UTC by JanuarAsprilla

2023-12-01 22:15 UTC, wfercanas requested changes

2023-12-01 22:15 UTC, wfercanas commented on src/januar_asprilla/html-css/netflix/index.html
En todas las imagenes, use la propiedad `object-fit: cover`, para que la foto no se deforme por vía de obligarla a tener las dimensiones del contenedor en el documento (hablo de las que están dentro de las listas, no la del fondo).

2023-12-01 22:15 UTC, wfercanas commented on src/januar_asprilla/html-css/netflix/index.html
> +            <div class="info-extras">
Este contenedor se está desbordando y usando parte del área del contenedor de abajo:
![image](https://github.com/selsa-inube/bootcamp/assets/36939686/3cc845d2-527a-4b06-8d63-d881a8bb1f9b)

2023-12-02 12:11 UTC, JanuarAsprilla commented on src/januar_asprilla/html-css/netflix/index.html
> +            <div class="info-extras">
corregido

2023-12-02 12:14 UTC, JanuarAsprilla commented on src/januar_asprilla/html-css/netflix/index.html
propiedad aplicada

2023-12-04 21:49 UTC, merged