lo/2/A2
selsa-inube/bootcamp pull request #480
Opened 2023-11-22 06:15 UTC by LinconOssa

2023-11-26 16:23 UTC, wfercanas requested changes

2023-11-26 16:23 UTC, wfercanas commented on src/Lincon/JS/A2/minimum.js
> +  return Math.min(valorUno, valorDos);
La idea del ejercicio es hacer una función que haga lo que hace `Math.min()`, por lo tanto usted debe implementar la lógica y no reutilizar esta función.

2023-11-26 16:23 UTC, wfercanas commented on src/Lincon/JS/A2/minimum.js
Use nombres de variables en inglés

2023-11-26 16:23 UTC, wfercanas commented on src/Lincon/JS/A2/recursion.js
> +  return isEven(number + 2);
Si el número es negativo, va a llegar a este return. Cualquiera que sea el número negativo, va a empezar a sumar de a dos en dos hasta que eventualmente llegue a 0 o 1 y ahí ya aplica los if de arriba.

Si revisa el enunciado, se define que esta función aplica para enteros positivos. Es preferible que respete esa restricción y no que extienda la responsabilidad de esta función.

Aparte, ¿Está validando que efectivamente los números sean enteros?

2023-11-26 16:23 UTC, wfercanas commented on src/Lincon/JS/A2/beancounting.js
> +  for (let a = 0; a < string.length; a++) {
La idea no es que use el contenido de `countChar`, sino que use directamente la función.

2023-11-26 16:23 UTC, wfercanas requested changes

2023-11-26 16:23 UTC, wfercanas commented on src/Lincon/JS/A2/beancounting.js
> +  let contador = 0;
Variables en inglés.

2023-11-27 14:44 UTC, LinconOssa commented on src/Lincon/JS/A2/minimum.js
> +  return Math.min(valorUno, valorDos);
Listo

2023-11-27 15:26 UTC, wfercanas approved these changes

2023-11-27 15:27 UTC, merged