Ja/3/a3
selsa-inube/bootcamp pull request #487
Opened 2023-11-26 18:52 UTC by JanuarAsprilla

2023-11-28 18:51 UTC, wfercanas requested changes

2023-11-28 18:51 UTC, wfercanas commented on src/januar_asprilla/JS/A3/a-list.js
> +  if (!lst) return undefined;
Aquí está validando si la lista es un elemento truthy o falsy, pero la lista como tal, la que llega como parámetro. Si quien usa la función no pasa una lista como parámetro, claramente no se puede ejecutar la lógica de la función para buscar el nth elemento. Sin embargo, ese no es el propósito del enunciado.

Lo que se intenta es que de forma progresiva vaya avanzando de lista anidada en lista anidada hasta encontrar el nth value. Si durante el camino se encuentra con una lista cuyo value es `null`, ahí ya no se puede buscar más y es ahí donde se necesita hacer un return `undefined`.

2023-11-28 18:51 UTC, wfercanas commented on src/januar_asprilla/JS/A3/deep-comparison.js
> +    objA == null ||
No funcionaría adecuadamente con `==` porque estaría permitiendo que javascript modifique los tipos. Por ejemplo, javascript dice que `undefined == null` es `true`

2023-11-28 18:51 UTC, wfercanas commented on src/januar_asprilla/JS/A3/the-sum-of-a-range.js
> +  }
Investigue e intente refactorizar esta función usando `arr.reduce()`

2023-11-29 02:29 UTC, JanuarAsprilla commented on src/januar_asprilla/JS/A3/a-list.js
> +function arrayToList(arr) {
corregido

2023-11-29 02:36 UTC, JanuarAsprilla commented on src/januar_asprilla/JS/A3/a-list.js
> +  for (let node = lst; node; node = node.rest) {
corregido

2023-11-29 02:36 UTC, JanuarAsprilla commented on src/januar_asprilla/JS/A3/a-list.js
> +  if (!lst) return undefined;
corregido

2023-11-29 02:38 UTC, JanuarAsprilla commented on src/januar_asprilla/JS/A3/deep-comparison.js
> +    objA == null ||
corregido 

se implemento agregar un tripe igual (===) para que sea mas estricto esa evaluación

2023-11-29 02:46 UTC, JanuarAsprilla commented on src/januar_asprilla/JS/A3/deep-comparison.js
> +    objA == null ||
corregido

se le agrego mas restricciones a la función

2023-11-29 02:46 UTC, JanuarAsprilla commented on src/januar_asprilla/JS/A3/deep-comparison.js
> +    objA == null ||
corregido
agregando a la función iguales (=) para que estos pongan mas restricciones dentro de la misma

2023-11-29 02:49 UTC, JanuarAsprilla commented on src/januar_asprilla/JS/A3/the-sum-of-a-range.js
> +  }
corregido
en el codigo utilizo arr.reduce() para acumular la suma de los elementos del arreglo

2023-11-30 15:06 UTC, merged