lo/8/A8
selsa-inube/bootcamp pull request #492
Opened 2023-11-30 00:55 UTC by LinconOssa

2023-12-06 20:31 UTC, wfercanas requested changes

2023-12-06 20:31 UTC, wfercanas commented on src/Lincon/JS/A8/Persistent group.js
> +PGroup.empty = new PGroup([]);
Este array vacío como parámetro se lo puede ahorrar aquí, si más bien hace una asignación por default en los parámetros de la función `constructor`

2023-12-06 20:31 UTC, wfercanas commented on src/Lincon/JS/A8/Persistent group.js
> +    if (this.has(parameter)) return this;
Si retorna `this`, está retornando la referencia a la instancia original. La idea de esta clase es evitar ese tipo de referencias que puedan implicar la mutación de una instancia anterior.

```js
let a = PGroup.empty.add("a");
let b = a.add("a");
console.log(a === b); // true
```
Lo mismo pasa abajo con la función `delete`

2023-12-06 20:31 UTC, wfercanas commented on src/Lincon/JS/A8/Persistent group.js
> +    const p = this.members.indexOf(parameter);
No es necesario buscar un índice para luego evaluar el índice. Ya tiene un método `has()` para este tipo de cosas.

2023-12-06 20:31 UTC, wfercanas commented on src/Lincon/JS/A8/Measuring a robot y Robot efficiency.js
> +  const runTask = (robot, state, memory) => {
¿Por qué necesita esta función si ya tiene la función `runRobot()`?

2023-12-06 22:51 UTC, LinconOssa commented on src/Lincon/JS/A8/Measuring a robot y Robot efficiency.js
> +    tasks.reduce((total, task) => total + runTask(robot, task, memory), 0);
![image](https://github.com/selsa-inube/bootcamp/assets/103295353/7e2e7cdc-97d4-4bf3-b4d2-3f73528e7160)
Completado

2023-12-06 22:51 UTC, LinconOssa commented on src/Lincon/JS/A8/Persistent group.js
> +PGroup.empty = new PGroup([]);
![image](https://github.com/selsa-inube/bootcamp/assets/103295353/15d83a30-9e1c-4765-b0c3-fe1385eaf3f1)
Completado

2023-12-06 22:52 UTC, LinconOssa commented on src/Lincon/JS/A8/Persistent group.js
> +    if (this.has(parameter)) return this;
Completado

2023-12-06 22:52 UTC, LinconOssa commented on src/Lincon/JS/A8/Persistent group.js
> +    const p = this.members.indexOf(parameter);
Completado

2023-12-07 00:38 UTC, LinconOssa commented on src/Lincon/JS/A8/Measuring a robot y Robot efficiency.js
> +  const runTask = (robot, state, memory) => {
Cambio listo

2023-12-11 16:43 UTC, wfercanas commented on src/Lincon/JS/A8/Persistent group.js
> +    if (this.has(parameter)) return this;
Falta el ajuste para el método "add"

2023-12-11 17:02 UTC, LinconOssa commented on src/Lincon/JS/A8/Persistent group.js
> +    if (this.has(parameter)) return this;
![image](https://github.com/selsa-inube/bootcamp/assets/103295353/8e85ae96-3578-4638-b42e-77b130169604)
Listo

2023-12-11 23:35 UTC, LinconOssa commented on src/Lincon/JS/A8/Persistent group.js
> +    if (this.has(parameter)) return this;
![image](https://github.com/selsa-inube/bootcamp/assets/103295353/a42981af-7a7b-4e77-9a92-dcc0935cd377)
Cambio listo

2023-12-13 20:59 UTC, wfercanas approved these changes

2023-12-13 20:59 UTC, merged