Ja/8/a8
selsa-inube/bootcamp pull request #493
Opened 2023-11-30 18:05 UTC by JanuarAsprilla

2023-12-06 20:09 UTC, wfercanas requested changes

2023-12-06 20:09 UTC, wfercanas commented on src/januar_asprilla/JS/A8/persistent-group.js
> +    return this;
Si hace estos `return this;` al no cumplirse la condición anterior, está retornando la referencia a la misma instancia que está siendo usada para ejecutar el método. Precisamente la idea es retornar un new PGroup para que se creen instancias nuevas y no se retornen referencias a las instancias anteriores.

Lo pruede comprobar si hace lo siguiente:
```js
let a = PGroup.empty.add("a");
let b = a.add("a");
console.log(a === b); // true
```

2023-12-06 21:03 UTC, JanuarAsprilla commented on src/januar_asprilla/JS/A8/measuring-a-robot.js
> +  for (let i = 0; i < numTasks; i++) {
corregido

2023-12-06 21:03 UTC, JanuarAsprilla commented on src/januar_asprilla/JS/A8/persistent-group.js
> +    this.members = members || [];
corregido

2023-12-06 21:20 UTC, JanuarAsprilla commented on src/januar_asprilla/JS/A8/persistent-group.js
> +    return PGroup._empty;
corregido

2023-12-11 16:42 UTC, wfercanas requested changes

2023-12-11 16:42 UTC, wfercanas commented on src/januar_asprilla/JS/A8/measuring-a-robot.js
> +      break;
Adicional al `console.log()`, puede hacer un return de `turns`. De esa manera cuando ejecute `runRobot()` la función le va a retornar la cantidad de turnos que utilizó.

2023-12-11 16:42 UTC, wfercanas commented on src/januar_asprilla/JS/A8/measuring-a-robot.js
> +  const resultsRobot2 = runRobots(robot2, memory2, tasks); // Ejecutar robot2
Aquí ya desacopló la generación de tasks de la ejecución de las mismas, lo que es preferible.

Sin embargo, luego de crear la lista de `tasks`, está usando una función llamada `runRobots()` que en concreto hace casi lo mismo que `runRobot()`, sólo que iterando por cada una de las task.

El problema es que tiene código relacionado con la gestión de la memoria y el state de un robot en ejecución en dos puntos diferentes del programa: `runRobot()` y `runRobots()`.

Sugerencias:
1. Refactorice `runRobot()` para que haga un return de la cantidad de turnos gastados.
2. Elimine `runRobots()`
3. Use `runRobot()` en cada iteración de las task para saber cuántos turnos demoró el robot en cuestión.

2023-12-11 17:33 UTC, JanuarAsprilla commented on src/januar_asprilla/JS/A8/measuring-a-robot.js
> +      break;
corregido

2023-12-11 18:15 UTC, JanuarAsprilla commented on src/januar_asprilla/JS/A8/measuring-a-robot.js
> +  const resultsRobot2 = runRobots(robot2, memory2, tasks); // Ejecutar robot2
corregido

2023-12-11 21:33 UTC, wfercanas approved these changes

2023-12-11 21:34 UTC, merged