Cr/8/robot
selsa-inube/bootcamp pull request #495
Opened 2023-12-05 12:21 UTC by carin91

2023-12-06 20:56 UTC, wfercanas requested changes

2023-12-06 20:56 UTC, wfercanas commented on src/carin/JS/A8/persistent_group.js
> +    this.content = [];
Esto implica que la única forma de inicializar un PGroup con un `new PGroup()` es con una instancia vacía. De nada serviría hacer algo como `new PGroup(["a", "b"])` porque obtendría una instancia vacía.

Creo que puede refactorizar para que esto sea posible.

2023-12-06 20:56 UTC, wfercanas commented on src/carin/JS/A8/persistent_group.js
> +      // return new PGroup(this.content);
Eliminar código comentado

2023-12-06 20:56 UTC, wfercanas commented on src/carin/JS/A8/persistent_group.js
> +    } else return this;
Si retorna this, está retornando la referencia a la instancia original. La idea es precisamente retornar una instancia nueva para evitar mutaciones de algún estilo en instancias anteriores.

```js
let a = PGroup.empty.add("a");
let b = a.add("a");
console.log(a === b); // true
```
Aplica también para el método `delete()`

2023-12-06 20:56 UTC, wfercanas commented on src/carin/JS/A8/persistent_group.js
> +      newPGroup.content.splice(this.content.indexOf(element), 1);
Es preferible utilizar un `filter`, que crea un array nuevo usando el filtro correspondiente, que buscar un índice y luego aplicar un `splice`.

Aquí tuvo el cuidado de aplicar el splice sobre un array al que puede afectar directamente en este punto del programa, pero mezclar en el código momentos en los cuales tengo permiso de mutar un elemento y momentos donde no, puede hacer que el mantenimiento del código sea más complicado. Es preferible mantenerse firme en la inmutabilidad en general.

2023-12-06 20:56 UTC, wfercanas commented on src/carin/JS/A8/persistent_group.js
> +      let newPGroup = PGroup.from(this.content);
Aquí se está pagando el precio de haber definido el constructor con sólo la posibilidad de crear grupos vacíos. 
Implementar el método `from` extende todavía más la clase y amplía el rango de funcionalidades que la clase tendría que soportar.

Es preferible refactorizar el constructor y no extender el componente en nuevas funcionalidades.

2023-12-06 20:56 UTC, wfercanas commented on src/carin/JS/A8/persistent_group.js
> +    if (this.content.indexOf(element) >= 0) {
Puede simplificar usando el método `array.includes()`

2023-12-06 20:56 UTC, wfercanas commented on src/carin/JS/A8/measuring_a_robot.js
> +      memory = action.memory;
Si ya tiene la función `runRobot()` que actualiza state y memory en la ejecución de un robot durante una tarea, ¿por qué implementa aquí de nuevo esa funcionalidad?

2023-12-06 20:56 UTC, wfercanas commented on src/carin/JS/A8/measuring_a_robot.js
> +      break;
Aquí es preferible hacer `return` de la cantidad de turnos que hacer sólo el `console.log()`

2023-12-12 14:11 UTC, carin91 commented on src/carin/JS/A8/persistent_group.js
> +    this.content = [];
attended
![image](https://github.com/selsa-inube/bootcamp/assets/123512032/c0b47251-5748-4a42-9e1c-708d5af12272)

2023-12-12 14:13 UTC, carin91 commented on src/carin/JS/A8/persistent_group.js
> +    } else return this;
attended
![image](https://github.com/selsa-inube/bootcamp/assets/123512032/0e48bdd0-d0f7-4b2f-9fdb-99212689ebee)

2023-12-12 14:14 UTC, carin91 commented on src/carin/JS/A8/persistent_group.js
> +    } else return this;
![image](https://github.com/selsa-inube/bootcamp/assets/123512032/530d9a52-4500-4f2e-9b07-3358e8776ea7)

2023-12-12 14:22 UTC, carin91 commented on src/carin/JS/A8/persistent_group.js
> +      newPGroup.content.splice(this.content.indexOf(element), 1);
attended
![image](https://github.com/selsa-inube/bootcamp/assets/123512032/3f5a6d47-3e03-4d2f-b67e-526a7fbb7dfc)

2023-12-12 14:23 UTC, carin91 commented on src/carin/JS/A8/persistent_group.js
> +      newPGroup.content.splice(this.content.indexOf(element), 1);
attended
![image](https://github.com/selsa-inube/bootcamp/assets/123512032/8b80315d-8869-4da7-aa59-528afaec30e2)

2023-12-12 14:26 UTC, carin91 commented on src/carin/JS/A8/persistent_group.js
> +      let newPGroup = PGroup.from(this.content);
attended
![image](https://github.com/selsa-inube/bootcamp/assets/123512032/1c30a36d-cf88-4382-a8e1-8886060cc4a5)

2023-12-12 14:31 UTC, carin91 commented on src/carin/JS/A8/measuring_a_robot.js
> +      memory = action.memory;
This is necessary due to the scope of the variables, the action and memory in lines 155 and 157 are restricted into the while scope, also, the memory and state in runRobot() are restricted to its scope.

There is no need to modify these lines.

2023-12-12 14:34 UTC, carin91 commented on src/carin/JS/A8/measuring_a_robot.js
> +      break;
attended
![image](https://github.com/selsa-inube/bootcamp/assets/123512032/4a10732f-3ddf-429e-b268-505fc8b6f9b3)

2023-12-13 20:57 UTC, wfercanas commented on src/carin/JS/A8/measuring_a_robot.js
> +      memory = action.memory;
No es cierto. `runRobot()` es una función que desacopla la ejecución de un robot específico y una tarea específica. Se implementa en el scope general del programa para que luego en las otras funciones donde usted necesite ejecutar un robot específico, no tenga que volver a contar parcels, actualizar memorias y modificar states.

Si en `runRobot()` retorna `turn` cuando ya no hay parcels, la función le va a decir cuántos pasos le tomó completar una tarea. Luego es sólo cuestión de iterar las 100 tareas random que creó y ejecutar `runRobot()` 100 veces para cada robot de interés.

Se mete en problemas de scope cuando crea `stepsPerTask()` dentro de `compareRobots()` y cuando  `stepsPerTask()` está haciendo varias de las responsabilidades que ya le fueron asignadas a `runRobot()`

2023-12-14 08:33 UTC, carin91 commented on src/carin/JS/A8/measuring_a_robot.js
> +      memory = action.memory;
attended
1) I deleted stepsPerTask()

![image](https://github.com/selsa-inube/bootcamp/assets/123512032/a15f06b1-31ee-4e50-b4ef-6c6694f1dfe1)

2) I modified runRobot() (i) deleting console.log() (ii) returning turns and deleting the break (it is not necessary anymore)
![image](https://github.com/selsa-inube/bootcamp/assets/123512032/12317940-3d81-4535-b6aa-9af0e3961edd)

2023-12-19 21:58 UTC, wfercanas approved these changes

2023-12-19 21:58 UTC, merged