Cr/27/google
selsa-inube/bootcamp pull request #498
Opened 2023-12-11 11:59 UTC by carin91

2023-12-13 20:43 UTC, wfercanas requested changes

2023-12-13 20:43 UTC, wfercanas commented on src/carin/A27/imgs/search.png:Zone.Identifier
Este archivo se puede eliminar

2023-12-13 20:43 UTC, wfercanas commented on src/carin/A27/index-a27.html
> +    <div id="sub-form"></div>
Este `div` vacío sobra

2023-12-13 20:43 UTC, wfercanas commented on src/carin/A27/index-a27.html
> +        </div>
La barra de búsqueda se está desbordando en responsive:
![image](https://github.com/selsa-inube/bootcamp/assets/36939686/7c388e03-73c2-4744-aa69-ebc17770dad6)

2023-12-13 20:43 UTC, wfercanas commented on src/carin/A27/index-a27.html
> +        </div>
Cuando ya no cabe la lista, está se está colocando abajo de forma correcta, pero por fuera del contenedor padre:
![image](https://github.com/selsa-inube/bootcamp/assets/36939686/b7774d92-77c0-4a11-92fc-46cd83df31a2)

2023-12-14 07:48 UTC, carin91 commented on src/carin/A27/index-a27.html
> +    <div id="sub-form"></div>
attended
It was included to (1) add to the page additional content for festivities and so on (2) to organize the sections accordingly to google.com, so, it was necessary to change display: flex to display: grid in body. It was also necessary to declare the row lines for the footer.

![image](https://github.com/selsa-inube/bootcamp/assets/123512032/ee35e5b0-36f7-4669-86fa-209b38e19eb5)

![image](https://github.com/selsa-inube/bootcamp/assets/123512032/8f074179-bc77-460b-bec2-9c1bc1382f09)

![image](https://github.com/selsa-inube/bootcamp/assets/123512032/47e92d7e-b6c1-4f59-a439-facfa504a1c7)

2023-12-14 08:04 UTC, carin91 commented on src/carin/A27/index-a27.html
> +        </div>
1) In device emulation is not overlaying

![image](https://github.com/selsa-inube/bootcamp/assets/123512032/2215d694-74f8-495d-9627-1a9fd06886e9)

2) In normal mode the behavior of google.com is similar, with the search bar overlaying

![image](https://github.com/selsa-inube/bootcamp/assets/123512032/df8045f3-c03d-4385-9945-fc66a4d5f9a2)

3) I fix the width declaration for the search, i had 2 width values (50vw and 400px), so i deleted the 400px line.
![image](https://github.com/selsa-inube/bootcamp/assets/123512032/88d1ab7c-0248-4be1-b449-91d125994f91)

2023-12-14 08:05 UTC, carin91 commented on src/carin/A27/index-a27.html
> +        </div>
Attended
I had a height value of 50px, i changed it to auto and add 50px value to min-height property.
![image](https://github.com/selsa-inube/bootcamp/assets/123512032/33a16edd-f4d2-4302-88d5-702e815891f9)

2023-12-19 22:06 UTC, wfercanas requested changes

2023-12-19 22:06 UTC, wfercanas commented on src/carin/A27/index-a27.html
El documento está utilizando más de 100vh y está apareciendo un scroll.

2023-12-20 08:43 UTC, carin91 commented on src/carin/A27/index-a27.html
attended
I changed the body height property from 100% to 100vh.
![image](https://github.com/selsa-inube/bootcamp/assets/123512032/9cb53517-8575-4033-9846-98ba43cfe2bd)

2023-12-20 08:43 UTC, carin91 commented on src/carin/A27/imgs/search.png:Zone.Identifier
attended
![image](https://github.com/selsa-inube/bootcamp/assets/123512032/82211ffe-dd33-4a5c-a1e5-2c0751eb2ea1)

2023-12-20 15:32 UTC, wfercanas approved these changes

2023-12-20 15:32 UTC, merged