feat: activity  completed
selsa-inube/bootcamp pull request #499
Opened 2023-12-11 19:20 UTC by JanuarAsprilla

2023-12-20 00:17 UTC, wfercanas requested changes

2023-12-20 00:17 UTC, wfercanas commented on src/januar_asprilla/JS/A17/the-locked-box.js
> +  }
Este `if` no es estrictamente necesario, puede ejecutar el `box.unlock()` de una. Si la caja está cerrada, la abre. Si está abierta, no pasa nada tampoco.

2023-12-20 00:17 UTC, wfercanas commented on src/januar_asprilla/JS/A17/the-locked-box.js
> +    body(); // ejecutamos la función proporcionada
Un `try` tiene sentido si por dentro hay instrucciones que por dentro pueden hacer throw de un error. En cuyo caso, el `catch` también es importante.

Agregue un `catch` para manerar los posibles errores que pueda retornar `body`.

2023-12-20 15:41 UTC, wfercanas commented on src/januar_asprilla/JS/A17/the-locked-box.js
> +  }
No era necesario borrar `wasLocked` porque con eso estaba resolviendo bien la parte de volver a cerrar la caja sólo si estaba cerrada en un principio.

Usted puede capturar el estado en `wasLocked` y luego directamente abrirla. Ya al final evalúa cómo estaba `wasLocked `en un comienzo para saber qué hacer en el `finally`

2023-12-20 17:42 UTC, JanuarAsprilla commented on src/januar_asprilla/JS/A17/the-locked-box.js
> +  }
corregido

2023-12-21 19:21 UTC, wfercanas approved these changes

2023-12-21 19:21 UTC, merged