cr/23/stella-studio
selsa-inube/bootcamp pull request #501
Opened 2023-12-12 14:05 UTC by carin91

2023-12-13 20:35 UTC, wfercanas requested changes

2023-12-13 20:35 UTC, wfercanas commented on src/carin/A23/index-a23.html
> +    <header>
La aplicación del fondo del header puede mejorarse. Cambio el color para exagerar y que se note más lo que está ocurriendo.

El fondo debería ocupar todo el ancho.

![image](https://github.com/selsa-inube/bootcamp/assets/36939686/11dd6893-04bf-42e0-818d-8949a7855a04)

2023-12-13 20:35 UTC, wfercanas commented on src/carin/A23/index-a23.html
> +      <nav>
Los links del nav no están quedando centrados. Como está usando flex, el espacio entre elementos es igual, pero el contenido de la izquierda (logo) es más ancho que el de la derecha (ícono).

Centrar.

![image](https://github.com/selsa-inube/bootcamp/assets/36939686/53b67f4d-04bb-48e5-9093-1288e7f4406c)

2023-12-13 20:35 UTC, wfercanas commented on src/carin/A23/index-a23.html
> +        </div>
Un botón se está desbordando:
![image](https://github.com/selsa-inube/bootcamp/assets/36939686/3d0be50a-8b09-4815-a649-133017c7f109)

2023-12-13 20:35 UTC, wfercanas commented on src/carin/A23/index-a23.html
> +          </ul>
Un elemento de la lista se está desbordando:
![image](https://github.com/selsa-inube/bootcamp/assets/36939686/3b36f1c0-3a1c-4c88-9f2f-a122c2b1fe3d)

2023-12-13 20:35 UTC, wfercanas commented on src/carin/A23/index-a23.html
> +        <div id="call-to-action-r">
Este `div` sólo contiene una lista `ul`. El `div` puede sobrar y dejar sólo la lista para simplificar el documento.

2023-12-14 06:37 UTC, carin91 commented on src/carin/A23/index-a23.html
> +    <header>
attended
![image](https://github.com/selsa-inube/bootcamp/assets/123512032/51f4a461-debf-47b5-8b7c-2afd995582ce)

2023-12-14 06:47 UTC, carin91 commented on src/carin/A23/index-a23.html
> +      <nav>
attended

1) display: grid for nav

![image](https://github.com/selsa-inube/bootcamp/assets/123512032/c891ad95-fb6a-47a3-9e1e-f4b2b281f1f6)

2) align-self: center for ul
![image](https://github.com/selsa-inube/bootcamp/assets/123512032/c09e7955-2b65-49c5-90cb-9196256335d7)

2023-12-14 07:03 UTC, carin91 commented on src/carin/A23/index-a23.html
> +        <div id="call-to-action-r">
attended
![image](https://github.com/selsa-inube/bootcamp/assets/123512032/ec4e0559-e6eb-4cc7-9c41-d441a995c899)

2023-12-14 07:33 UTC, carin91 commented on src/carin/A23/index-a23.html
> +        </div>
attended
Trying different things i found a display option called "contents" which resolves this issue

![image](https://github.com/selsa-inube/bootcamp/assets/123512032/8cc0c497-99a8-4052-a5ab-801b4e394b88)

2023-12-14 07:35 UTC, carin91 commented on src/carin/A23/index-a23.html
> +          </ul>
Attended, through trial and error i think the ul box size ignores the margin of its children, so, i delete this margin and assign as a padding in the final descendant.

![image](https://github.com/selsa-inube/bootcamp/assets/123512032/723f70c0-c7c1-46d7-be2a-f76ca75a8224)

2023-12-14 07:38 UTC, carin91 commented on src/carin/A23/index-a23.html
> +      <nav>
3) include an additional selector in media to include the 2 column grid
![image](https://github.com/selsa-inube/bootcamp/assets/123512032/2a96c75f-e8b6-4a2b-bc5c-413a907e0ecd)

2023-12-19 22:20 UTC, wfercanas approved these changes

2023-12-19 22:20 UTC, merged