Cr/29/netflix
selsa-inube/bootcamp pull request #504
Opened 2023-12-13 20:50 UTC by carin91

2023-12-19 22:49 UTC, wfercanas requested changes

2023-12-19 22:49 UTC, wfercanas commented on src/carin/html-css/A29/index.html
> +    <main>
El cuerpo del poster lleva un degradado hacia el negro abajo, para que las letras se vean bien.

2023-12-19 22:49 UTC, wfercanas commented on src/carin/html-css/A29/index.html
> +                <img src="imgs/thimothe-pic.jpeg" alt="Timothée Chalamet pic" />
Ajuste la propiedad `object-fit` de estas imágenes al valor `cover` para que no se vean como aplastadas.

2023-12-19 22:49 UTC, wfercanas commented on src/carin/html-css/A29/styles.css
> +  padding: 0 auto 0 auto;
Si utiliza `auto`, debe usar la versión abreviada de la propiedad, si no el navegador protesta:
`padding: 0 auto`

2023-12-19 22:49 UTC, wfercanas commented on src/carin/html-css/A29/styles.css
> +  font-size: 0.7rem !important;
No es buena práctica usar los `!important`, revise el uso de selectores para evitar esta funcionalidad.

https://dev.to/alvaromontoro/using-important-in-css-75c

2023-12-20 08:49 UTC, carin91 commented on src/carin/html-css/A29/index.html
> +    <main>
attended
![image](https://github.com/selsa-inube/bootcamp/assets/123512032/e916a37a-1918-4523-bc27-9990f852e607)

2023-12-20 08:50 UTC, carin91 commented on src/carin/html-css/A29/index.html
> +                <img src="imgs/thimothe-pic.jpeg" alt="Timothée Chalamet pic" />
attended
![image](https://github.com/selsa-inube/bootcamp/assets/123512032/86c87d4c-ff1f-434d-bcdc-1e2f7a1124de)

2023-12-20 08:51 UTC, carin91 commented on src/carin/html-css/A29/styles.css
> +  padding: 0 auto 0 auto;
attended
![image](https://github.com/selsa-inube/bootcamp/assets/123512032/7726a731-df06-4b72-b11d-02662cc17866)

2023-12-20 09:00 UTC, carin91 commented on src/carin/html-css/A29/styles.css
> +  font-size: 0.7rem !important;
attended
![image](https://github.com/selsa-inube/bootcamp/assets/123512032/a0644337-58a4-48dc-b424-d3c3842ff783)

2023-12-20 15:37 UTC, merged