feat: new a20 version
selsa-inube/bootcamp pull request #506
Opened 2023-12-14 11:53 UTC by carin91

2023-12-21 20:23 UTC, wfercanas requested changes

2023-12-21 20:23 UTC, wfercanas commented on src/carin/JS/A20/build_a_table.js
> +  let colNames = (data) => {
Esta función es pura, por lo que bien podría estar por fuera del scope de la función `createTable` para reducir el anidamiento.

2023-12-21 20:23 UTC, wfercanas commented on src/carin/JS/A20/build_a_table.js
> +        bodyCell.style.textAlign = "right";
Refactorice para que aquí no se apliquen estilos CSS directamente. Agregue una clase con js y luego sí aplique estilos a esa clase.

https://developer.mozilla.org/en-US/docs/Web/API/Element/classList

2023-12-21 20:23 UTC, wfercanas commented on src/carin/JS/A20/build_a_table.js
> +  let rowBody = (rowData, headNames) => {
Esta función rowBody también es pura, por lo que igualmente podría dejarla por fuera del scope de `createTable`

2023-12-21 20:28 UTC, carin91 commented on src/carin/JS/A20/build_a_table.js
> +  let colNames = (data) => {
attended
![image](https://github.com/selsa-inube/bootcamp/assets/123512032/9c14d3b2-e210-4f2b-b3ea-c0ae982227a0)

2023-12-21 20:31 UTC, carin91 commented on src/carin/JS/A20/build_a_table.js
> +        bodyCell.style.textAlign = "right";
attended:

1) Defining the className
![image](https://github.com/selsa-inube/bootcamp/assets/123512032/0825c843-5d4f-4a74-bf48-72d7f043824b)
2) Adding styles in html
![image](https://github.com/selsa-inube/bootcamp/assets/123512032/a29b335a-bd50-4393-9aac-c50d83adf346)

2023-12-21 20:32 UTC, carin91 commented on src/carin/JS/A20/build_a_table.js
> +  let rowBody = (rowData, headNames) => {
attended
![image](https://github.com/selsa-inube/bootcamp/assets/123512032/6f763419-a4d7-43ad-929f-6d1a81e2440d)

2023-12-22 16:14 UTC, wfercanas approved these changes

2023-12-22 16:14 UTC, merged