lo/20/A20
selsa-inube/bootcamp pull request #507
Opened 2023-12-15 14:48 UTC by LinconOssa

2023-12-21 20:00 UTC, wfercanas requested changes

2023-12-21 20:31 UTC, LinconOssa commented on src/Lincon/JS/A20/Build a table.html
> +              num.style.textAlign = "right";
![image](https://github.com/selsa-inube/bootcamp/assets/103295353/757e12ab-831c-420a-8c70-f494bfe15ff1)
Listo

2023-12-21 20:31 UTC, LinconOssa commented on src/Lincon/JS/A20/Elements by tag name.html
> +          for (var i = 0; i < currentNode.childNodes.length; i++) {
![image](https://github.com/selsa-inube/bootcamp/assets/103295353/a1d502b7-5877-4892-a11d-2e762a66d92d)
Listo

2023-12-22 16:11 UTC, wfercanas approved these changes

2023-12-22 16:11 UTC, merged