lo/21/A21
selsa-inube/bootcamp pull request #508
Opened 2023-12-15 16:16 UTC by LinconOssa

2023-12-22 23:11 UTC, wfercanas requested changes

2023-12-22 23:11 UTC, wfercanas commented on src/Lincon/JS/A21/Mause Trail.html
> +      const numTrails = 1;
La idea es que se genere una cola, por lo que la cantidad debería ser de 5 o algo así.

2023-12-22 23:11 UTC, wfercanas commented on src/Lincon/JS/A21/Mause Trail.html
> +
Una forma de crear la cola es que cada trail se demore más tiempo en la transición: 
```js
trails.forEach((trail, index) => {
  trail.style.transitionDuration = `${index * 50}ms`;
});
```

2023-12-22 23:11 UTC, wfercanas commented on src/Lincon/JS/A21/Mause Trail.html
> +          const offset = index;
No creo que haga falta un offset

2023-12-23 00:10 UTC, LinconOssa commented on src/Lincon/JS/A21/Mause Trail.html
> +      const numTrails = 1;
Listo
![image](https://github.com/selsa-inube/bootcamp/assets/103295353/e44ff631-bfe9-4b02-b2c5-1b4413e4ddf8)

2023-12-23 00:10 UTC, LinconOssa commented on src/Lincon/JS/A21/Mause Trail.html
> +
![image](https://github.com/selsa-inube/bootcamp/assets/103295353/baa5a4b5-68a8-4285-80bd-5702ba219b41)
Listo

2023-12-23 00:11 UTC, LinconOssa commented on src/Lincon/JS/A21/Mause Trail.html
> +          const offset = index;
Listo eliminado

2023-12-27 20:00 UTC, wfercanas approved these changes

2023-12-27 20:00 UTC, merged