Ja/20/a20
selsa-inube/bootcamp pull request #509
Opened 2023-12-16 02:44 UTC by JanuarAsprilla

2023-12-21 19:53 UTC, wfercanas requested changes

2023-12-21 19:53 UTC, wfercanas commented on src/januar_asprilla/JS/A20/Build a table/assets/js/main.js
> +  for (var i = 0; i < keys.length; i++) {
Refactorice usando un `for..of`. Si arriba creó la variable como atributos, aquí sería algo como:
```js
for (let attribute of attributes) {
}
```

https://developer.mozilla.org/es/docs/Web/JavaScript/Reference/Statements/for...of

2023-12-21 19:53 UTC, wfercanas commented on src/januar_asprilla/JS/A20/Build a table/assets/js/main.js
> +  for (var ii = 0; ii < arrayOfObjects.length; ii++) {
Refactorice usando un `for..of`
Aquí sería algo como:
```js
for (let mountain of mountains) {
}
```

2023-12-21 19:53 UTC, wfercanas commented on src/januar_asprilla/JS/A20/Build a table/assets/js/main.js
> +function buildTable(arrayOfObjects) {
Renombre el parámetro como `mountains`. Es más diciente de lo que le está pasando.

2023-12-21 19:53 UTC, wfercanas commented on src/januar_asprilla/JS/A20/Build a table/assets/js/main.js
> +    table.appendChild(row);
Es preferible dejar el append de toda la row cuando ya tenga toda la fila armada. Cuando ya le haya incluido todos los datos correspondientes.

2023-12-21 19:53 UTC, wfercanas commented on src/januar_asprilla/JS/A20/Build a table/assets/js/main.js
> +    for (var iii = 0; iii < keys.length; iii++) {
Refactorice usando un `for..of`

2023-12-21 19:53 UTC, wfercanas commented on src/januar_asprilla/JS/A20/Build a table/assets/js/main.js
> +  var keys = Object.keys(arrayOfObjects[0]);
**Sugerencia**: no llame la variable `keys`, que es una palabra más cercana a javascript que al problema que está resolviendo. Preferiblemente llame la variable `attributes` o algo así

2023-12-21 19:53 UTC, wfercanas commented on src/januar_asprilla/JS/A20/Build a table/assets/js/main.js
> +        cell.style.textAlign = "right";
Es preferible no mezclar estilos con la lógica de la tabla. Aquí le sugiero que en lugar de disparar el estilo directo, agregue una clase css a la celda.
Luego en CSS puede agregar el text-align para esa clase.

https://developer.mozilla.org/en-US/docs/Web/API/Element/classList

2023-12-21 19:53 UTC, wfercanas commented on src/januar_asprilla/JS/A20/Elements by tag name/assets/js/main.js
La idea de este ejercicio es no usar `getElementsByTagName()` y más bien crear nuestra propia implementación.
Justo abajo del ejercicio dentro de la lectura le dan un par de pistas sobre cómo podría orientar la respuesta.

2023-12-22 12:58 UTC, JanuarAsprilla commented on src/januar_asprilla/JS/A20/Elements by tag name/assets/js/main.js
corregido

2023-12-22 13:09 UTC, JanuarAsprilla commented on src/januar_asprilla/JS/A20/Build a table/assets/js/main.js
> +        cell.style.textAlign = "right";
corregido

2023-12-22 13:42 UTC, JanuarAsprilla commented on src/januar_asprilla/JS/A20/Build a table/assets/js/main.js
> +  var keys = Object.keys(arrayOfObjects[0]);
corregido

2023-12-22 13:46 UTC, JanuarAsprilla commented on src/januar_asprilla/JS/A20/Build a table/assets/js/main.js
> +    for (var iii = 0; iii < keys.length; iii++) {
corregido

2023-12-22 13:49 UTC, JanuarAsprilla commented on src/januar_asprilla/JS/A20/Build a table/assets/js/main.js
> +  for (var i = 0; i < keys.length; i++) {
corregido

2023-12-22 13:49 UTC, JanuarAsprilla commented on src/januar_asprilla/JS/A20/Build a table/assets/js/main.js
> +  for (var ii = 0; ii < arrayOfObjects.length; ii++) {
corregido

2023-12-22 13:49 UTC, JanuarAsprilla commented on src/januar_asprilla/JS/A20/Build a table/assets/js/main.js
> +function buildTable(arrayOfObjects) {
corregido

2023-12-22 13:49 UTC, JanuarAsprilla commented on src/januar_asprilla/JS/A20/Build a table/assets/js/main.js
> +    table.appendChild(row);
corregido

2023-12-22 16:05 UTC, wfercanas commented on src/januar_asprilla/JS/A20/Build a table/assets/js/main.js
> +  for (var i = 0; i < keys.length; i++) {
Sigue faltando el `for..of`

2023-12-22 16:07 UTC, wfercanas commented on src/januar_asprilla/JS/A20/Build a table/assets/js/main.js
> +    table.appendChild(row);
Todavía está haciendo append de la row en la tabla en primer lugar. 
Primero haga append sobre las celdas en la row y luego sí hace append de la row en la table.

2023-12-22 16:15 UTC, JanuarAsprilla commented on src/januar_asprilla/JS/A20/Build a table/assets/js/main.js
> +  for (var i = 0; i < keys.length; i++) {
corregido este aspecto

2023-12-22 16:17 UTC, JanuarAsprilla commented on src/januar_asprilla/JS/A20/Build a table/assets/js/main.js
> +    table.appendChild(row);
corregido este aspecto

2023-12-22 16:50 UTC, wfercanas approved these changes

2023-12-22 16:51 UTC, merged