Ja/21/a21
selsa-inube/bootcamp pull request #510
Opened 2023-12-16 03:00 UTC by JanuarAsprilla

2023-12-22 23:02 UTC, wfercanas requested changes

2023-12-25 21:52 UTC, JanuarAsprilla commented on src/januar_asprilla/JS/A21/Mouse trail/assets/css/style.css
> +  border-radius: 3px;
corregido, se refactoriza el border-radius de **"3px"** a **"50%"**

2023-12-25 21:59 UTC, JanuarAsprilla commented on src/januar_asprilla/JS/A21/Mouse trail/assets/js/main.js
> +});
corregido, inclusión de la función **trails.forEach** ya que esta modifica la velocidad del Trail

2023-12-25 22:00 UTC, JanuarAsprilla commented on src/januar_asprilla/JS/A21/Mouse trail/assets/js/main.js
> +const numTrails = 10;
corregido, modificado el numero de trails

2023-12-25 22:03 UTC, JanuarAsprilla commented on src/januar_asprilla/JS/A21/Mouse trail/assets/js/main.js
> +    trail.style.top = event.pageY - offset + "px";
corregido, además comprendido el tema de **Rendimiento de procesamiento**

2023-12-27 19:57 UTC, wfercanas approved these changes

2023-12-27 19:57 UTC, merged