cr/30/tnyt
selsa-inube/bootcamp pull request #581
Opened 2023-12-20 13:11 UTC by carin91

2023-12-27 21:58 UTC, wfercanas requested changes

2023-12-27 21:58 UTC, wfercanas commented on src/carin/html-css/A30/styles.css
> +  display: grid;
No es necesario colocar un grid para que el documento fluya verticalmente. Este grid sobra.

2023-12-27 21:58 UTC, wfercanas commented on src/carin/html-css/A30/index.html
> +    <hr />
Estos `hr` tienen un `margin-top` muy grande. Es preferible quitar ese `margin`.

2023-12-27 21:58 UTC, wfercanas commented on src/carin/html-css/A30/index.html
> +          <li><a href="#">World</a></li>
La lista es flex pero está acomodando los ítems de la lista usando margin. 
Quizá tenga más sentido que no use el margin y más bien utilice algo como `justify-content: space-evenly`.

2023-12-27 21:58 UTC, wfercanas commented on src/carin/html-css/A30/styles.css
> +  grid-template-rows: 1fr auto;
Definir una altura como 1fr, significa que existe una altura ya definida y que esa altura se va a ir repartiendo en fracciones. Lo mismo que los fr en el ancho, que se reparten el width del contenedor.

Aquí como no hay tal alto, se ve obligado a ponerle un height al nav anidado.

**Conclusión**: le sugiero que en vez de crear una grilla de dos filas, deje sólo la grilla de una fila y 3 columnas para las noticias y más bien este nav anidado quede por fuera y defina su altura y tal de forma autónoma.

2023-12-30 22:50 UTC, carin91 commented on src/carin/html-css/A30/styles.css
> +  display: grid;
attended 
![image](https://github.com/selsa-inube/bootcamp/assets/123512032/a85aa442-ce57-4bf3-a40d-3405acd1581e)

2023-12-30 22:56 UTC, carin91 commented on src/carin/html-css/A30/index.html
> +    <hr />
attended

It was necessary due to the distance between hr and the article, so, i decided to assign a padding bottom for the article.
![image](https://github.com/selsa-inube/bootcamp/assets/123512032/b2ab2891-f016-475a-9be5-d2485cee65f1)

2023-12-30 22:58 UTC, carin91 commented on src/carin/html-css/A30/index.html
> +          <li><a href="#">World</a></li>
attended
![image](https://github.com/selsa-inube/bootcamp/assets/123512032/14912eb4-3dbb-4920-93d0-b6f12cc66940)

2023-12-30 23:03 UTC, carin91 commented on src/carin/html-css/A30/styles.css
> +  grid-template-rows: 1fr auto;
Partially attended:
1) I deleted the height in the nested nav.
2) I replace 1fr with 10vh. This produces the same result.
![image](https://github.com/selsa-inube/bootcamp/assets/123512032/6fbf1ede-1f7f-449c-a9f7-313f34af27f7)

The reason why i want to stick with the original solution is due to semantics. The nav-bar is related with the article, in fact, is related to the #main-section, so i think it is better to hold the current solution.

2024-01-02 15:07 UTC, wfercanas approved these changes

2024-01-02 15:07 UTC, merged