cr/21/events
selsa-inube/bootcamp pull request #584
Opened 2023-12-21 18:28 UTC by carin91

2023-12-22 23:32 UTC, wfercanas requested changes

2023-12-22 23:32 UTC, wfercanas commented on src/carin/JS/A21/mouse_trail.html
> +  trailElement.style.top = posY + "px";
Evite utilizar las propiedades `left` y `top` que corresponden al position. Estas propiedades hacen que el navegador deba pasar por los pasos de layout, paint y composite cada vez que exista un cambio en ellas.

Si utiliza la propiedad `transform` solamente se requiere el paso de composite. Si extiende la cantidad de puntos a 10 o algo así, va a ver que se pone muy lento si no hace este cambio.

2023-12-22 23:32 UTC, wfercanas commented on src/carin/JS/A21/mouse_trail.html
> +  let trailElement = document.getElementById("trailElement");
La idea es crear una cola, por lo tanto, se requiere crear más de un círculo.

2023-12-22 23:32 UTC, wfercanas commented on src/carin/JS/A21/mouse_trail.html
> +  let trailElement = document.getElementById("trailElement");
El efecto de cola lo puede lograr si a cada círculo le toma un tiempo diferente pasar de un punto A a un punto B.

2023-12-22 23:32 UTC, wfercanas commented on src/carin/JS/A21/tabs.html
> +      tabs.map((tab) => {
Este `map` no está retornando nada. Si no quiere retornar nada, es preferible usar un `forEach`

2023-12-22 23:32 UTC, wfercanas commented on src/carin/JS/A21/tabs.html
> +        tab.button.style.fontSize = selected ? "2rem" : "1rem";
En lugar de modificar así los estilos en esta función, puede crear una clase que se llame "selected". Con CSS coloca cuáles son los estilos que aplican cuando esté seleccionada una tab y aquí lo que hace es agregar o quitar la clase según aplique: `button.classList.remove` o `button.classList.add`.

2023-12-22 23:32 UTC, wfercanas commented on src/carin/JS/A21/tabs.html
> +      let tab = { node, button };
Está devolviendo un objeto sólo porque más abajo va a preguntar nuevamente `node.getAttribute`. Si ya arriba definió que `button.id === node.getAttribute`, el button ya está transportando la información necesaria para esa pregunta. 
Por lo tanto, no sería necesario retornar una estructura de datos más compleja de lo necesario. Podría retornar los button directamente y abajo comparar directamente `button.id === e.target.id`

2023-12-27 07:09 UTC, carin91 commented on src/carin/JS/A21/mouse_trail.html
> +  trailElement.style.top = posY + "px";
attended
![image](https://github.com/selsa-inube/bootcamp/assets/123512032/ae8f0abc-6e6f-4057-8d49-4c0ea4d859e9)

2023-12-27 08:26 UTC, carin91 commented on src/carin/JS/A21/mouse_trail.html
> +  let trailElement = document.getElementById("trailElement");
Attended
I decided to create the mouse trail through clicks

![image](https://github.com/selsa-inube/bootcamp/assets/123512032/69eb3339-2e48-4b93-97d0-c1321e642d43)

So, i need to change my "mousemove" event listener
![image](https://github.com/selsa-inube/bootcamp/assets/123512032/7b1bbe0b-ed4c-4561-98e0-188f0a9c9326)

I decided to admit a maximum trail length of 100
![image](https://github.com/selsa-inube/bootcamp/assets/123512032/f8c8efc0-16f1-40bc-a8f0-ba570b305362)

2023-12-27 08:28 UTC, carin91 commented on src/carin/JS/A21/mouse_trail.html
> +  let trailElement = document.getElementById("trailElement");
Attended in the previous issue

2023-12-27 08:29 UTC, carin91 commented on src/carin/JS/A21/tabs.html
> +      tabs.map((tab) => {
attended

2023-12-27 08:37 UTC, carin91 commented on src/carin/JS/A21/tabs.html
> +        tab.button.style.fontSize = selected ? "2rem" : "1rem";
attended
![image](https://github.com/selsa-inube/bootcamp/assets/123512032/586ce0e1-7571-41ff-a73b-44bceafd91c2)

2023-12-27 09:19 UTC, carin91 commented on src/carin/JS/A21/tabs.html
> +      let tab = { node, button };
not attended

The task is composed by 2 requirements:
1) To disappear the tab
2) To modify the styles of the selected button.

For the first requirement the tab should be known inside the handler, for instance, i need to pass the tabs to the handler.

I think about it before the first PR, but did not try to do it. For this, i try in different ways and i think this is more complex than the current solution. The firs try was to pass the node directly, and it works, for showing 1 tab but not for deleting the display for the others. So, i need the full array of {tab, button} to modified the tab styles or passing the full tab-panel as follows.

![image](https://github.com/selsa-inube/bootcamp/assets/123512032/dd5c2729-1e49-4a58-b663-6af0aa42445f)

2023-12-27 20:04 UTC, wfercanas approved these changes

2023-12-27 20:04 UTC, merged