cr/31/weather
selsa-inube/bootcamp pull request #586
Opened 2023-12-22 09:01 UTC by carin91

2024-01-03 15:48 UTC, wfercanas requested changes

2024-01-03 15:48 UTC, wfercanas commented on src/carin/html-css/A31/index.html
Hizo el desarrollo con la ventana de responsive abierta y definió el tamaño de la imagen con respecto al viewport. Esto hace que el proyecto funcione sólo para el ancho de pantalla particular que usted haya tenido cuando trabajó. Corrija las dimensiones.

![image](https://github.com/selsa-inube/bootcamp/assets/36939686/436e75e2-fc83-4439-a801-96c8663e88bf)

2024-01-04 11:23 UTC, carin91 commented on src/carin/html-css/A31/index.html
Attended:
1) 39 #upper-section { max-width: 425px;}
2) 117 main { max-width: 382px;}
3) 122 main > img { width: 60%;} //it was in 50vw;

2024-01-04 16:51 UTC, wfercanas approved these changes

2024-01-04 16:51 UTC, merged