cr/4/tic-tac-toe
selsa-inube/bootcamp pull request #634
Opened 2023-12-27 15:58 UTC by carin91

2024-01-02 16:09 UTC, wfercanas requested changes

2024-01-02 16:09 UTC, wfercanas commented on src/carin/react/A4/src/App.jsx
> +  function renderSquare(i) {
Aquí está anidando un componente de react dentro de otro componente. Es preferible que cada componente esté el el mayor nivel del módulo/archivo y no que esté anidado.

2024-01-02 16:09 UTC, wfercanas commented on src/carin/react/A4/src/App.jsx
> +import { faStepForward } from "@fortawesome/free-solid-svg-icons";
Esta variable se está importando pero no se usa. Puede borrarla.

2024-01-02 16:09 UTC, wfercanas commented on src/carin/react/A4/package.json
> +  "dependencies": {
Falta instalar `styled-components`

2024-01-02 16:09 UTC, wfercanas commented on src/carin/react/A4/src/App.jsx
Hace falta la funcionalidad de regresar a un turno anterior.

2024-01-02 16:09 UTC, wfercanas commented on src/carin/react/A4/src/App.jsx
> +      $inputColor={tik == "1" ? "red" : tik == "0" ? "blue" : "black"}
En la medida de lo posible, evite usar evaluaciones ternarias anidadas.

2024-01-02 17:28 UTC, carin91 commented on src/carin/react/A4/src/App.jsx
> +  function renderSquare(i) {
attended:
1) The renderSquare function and the Square components were displaced outside the Board component.
![image](https://github.com/selsa-inube/bootcamp/assets/123512032/77e29f51-8443-41f4-9c97-b38041c23e89)
2) Due to the scope of some states and variables it was necessary to add some args in the renderSquare function.
![image](https://github.com/selsa-inube/bootcamp/assets/123512032/ffb25d49-4783-4109-93d2-8392faad55f3)
![image](https://github.com/selsa-inube/bootcamp/assets/123512032/73104e18-aa0e-46c5-9eef-addde3a9aec7)

2024-01-02 17:29 UTC, carin91 commented on src/carin/react/A4/src/App.jsx
> +import { faStepForward } from "@fortawesome/free-solid-svg-icons";
attended

2024-01-02 17:32 UTC, carin91 commented on src/carin/react/A4/package.json
> +  "dependencies": {
attended
package.json

![image](https://github.com/selsa-inube/bootcamp/assets/123512032/02a22528-8b84-4d53-9c6d-0b2d38e95d1b)

2024-01-02 17:50 UTC, carin91 commented on src/carin/react/A4/src/App.jsx
> +      $inputColor={tik == "1" ? "red" : tik == "0" ? "blue" : "black"}
attended
I created a new colorOfSquare function using switch case (for experimenting) 

![image](https://github.com/selsa-inube/bootcamp/assets/123512032/50e9ec5e-d364-4f6c-b0dd-57f9ac9a563f)

2024-01-03 15:51 UTC, wfercanas commented on src/carin/react/A4/src/App.jsx
Todavía falta esta funcionalidad.

2024-01-05 08:40 UTC, carin91 commented on src/carin/react/A4/src/App.jsx
attended

2024-01-05 20:48 UTC, wfercanas approved these changes

2024-01-05 20:48 UTC, merged