ja/react/A2
selsa-inube/bootcamp pull request #637
Opened 2023-12-29 01:23 UTC by JanuarAsprilla

2024-01-02 15:40 UTC, wfercanas requested changes

2024-01-02 15:40 UTC, wfercanas commented on src/januar_asprilla/html-css/new-york-times/index.html
> +            </ItemContainer>
Estos styled-components en el index.html de la tarea de html-css no tienen sentido, le va a aparecer algo como esto:
![image](https://github.com/selsa-inube/bootcamp/assets/36939686/a47b488d-7dfa-4ad9-b8b6-064f67d38f38)

**No es necesario hacer modificaciones en esa tarea.**

2024-01-02 15:40 UTC, wfercanas commented on src/januar_asprilla/react/A2/src/Components/ImagensNoticeComponent/index.jsx
Todo lo que vaya por dentro de la carpeta Components, se supone que son componentes. Por lo tanto, no hace falta que a cada carpeta le coloque "Component" (ej: footerComponent, buttonComponent, etc.).

2024-01-02 15:40 UTC, wfercanas commented on src/januar_asprilla/react/A2/src/Components/ImagensNoticeComponent/imgNoticeStyle.js
Le sugiero que para todos los styled-components, los nombre empezando con la palabra Styled. De esa manera, luego en los jsx es más fácil identificar cuándo está uno hablando de un styled-component y cuándo de otro componente importado.

Para este archivo: StyledImage, StyledImagePreview, StyledImageCard, etc.

**El ajuste aguanta hacerlo para todos los archivos styles.js**

2024-01-02 15:40 UTC, wfercanas commented on src/januar_asprilla/react/A2/src/Components/buttonComponents/buttonStyled.js
> +function color() {
Esta función la puede borrar porque no la está usando en ningún lado

2024-01-02 15:40 UTC, wfercanas commented on src/januar_asprilla/react/A2/src/Components/footerComponent/index.jsx
> +        <ContainerCard background={"#c82b43"}>
En vez de estar repitiendo los códigos hexadecimales a la hora de pasar las props, puede crear una variable para cada color y luego pasar la variable a la prop background.
De esa manera, si luego cambia el color, no tiene que ir elemento por elemento cambiando el hexadecimal, sino que sólo se lo cambia una vez a la variable y ya.

2024-01-02 15:40 UTC, wfercanas commented on src/januar_asprilla/react/A2/src/Components/footerComponent/index.jsx
> +          <ItemList href="#" label="dealBook" />
Todos estos ItemList se pueden generar usando el método map. Para eso, tendría que tener una variable con los textos. Por ejemplo:

```js
items = [
  { id: 1, label: "Tech" }, 
  { id: 2, label: "Econ" }, 
  { id: 3, label: "Media" }, 

  ...
]

<ListNav>
  {items.map(item => <ItemList key={item.id} href="#" label={item.label} />)}
</ListNav>
```

2024-01-02 15:40 UTC, wfercanas commented on src/januar_asprilla/react/A2/src/Components/footerComponent/index.jsx
> +        <ContainerCard background={"#c82b43"}>
Todas estas `ContainerCard` también las puede generar con un `map`. Parecido a lo que le pedí con respecto a los ItemList, aquí necesita un objeto que guarde la información de cada tarjeta. De esa manera en el map puede generar cada card y no tiene que escribir cada una a mano.

2024-01-02 15:40 UTC, wfercanas commented on src/januar_asprilla/react/A2/src/Components/headerComponent/index.jsx
> +        <ListNav>
Esta lista también se puede generar usando un `map` y no escribiendo cada item a mano.

2024-01-02 15:40 UTC, wfercanas commented on src/januar_asprilla/react/A2/src/Components/mainComponent/index.jsx
> +        <ListNav>
Generar lista con un `map`

2024-01-02 15:40 UTC, wfercanas commented on src/januar_asprilla/react/A2/src/Components/mainComponent/index.jsx
> +        <NoticeSectionsCenter>
Generar lista de latest news usando `map`

2024-01-02 15:40 UTC, wfercanas commented on src/januar_asprilla/react/A2/src/Components/mainComponent/index.jsx
> +          <Captionections>Fast Forward</Captionections>
Generar sección de Fast forward usando `map`

2024-01-03 23:33 UTC, JanuarAsprilla commented on src/januar_asprilla/html-css/new-york-times/index.html
> +            </ItemContainer>
corregido, se eliminaron esos styled-components en el index.html

2024-01-03 23:57 UTC, JanuarAsprilla commented on src/januar_asprilla/react/A2/src/Components/ImagensNoticeComponent/imgNoticeStyle.js
ajuste realizado en todos los archivos

2024-01-03 23:58 UTC, JanuarAsprilla commented on src/januar_asprilla/react/A2/src/Components/buttonComponents/buttonStyled.js
> +function color() {
corregido, función eliminada

2024-01-04 00:14 UTC, JanuarAsprilla commented on src/januar_asprilla/react/A2/src/Components/footerComponent/index.jsx
> +        <ContainerCard background={"#c82b43"}>
corregido

2024-01-04 02:58 UTC, JanuarAsprilla commented on src/januar_asprilla/react/A2/src/Components/footerComponent/index.jsx
> +        <ContainerCard background={"#c82b43"}>
corregido

2024-01-04 02:58 UTC, JanuarAsprilla commented on src/januar_asprilla/react/A2/src/Components/footerComponent/index.jsx
> +          <ItemList href="#" label="dealBook" />
corregidas

2024-01-04 02:59 UTC, JanuarAsprilla commented on src/januar_asprilla/react/A2/src/Components/mainComponent/index.jsx
> +        <ListNav>
corregido

2024-01-04 03:22 UTC, JanuarAsprilla commented on src/januar_asprilla/react/A2/src/Components/headerComponent/index.jsx
> +        <ListNav>
corregido

2024-01-04 06:09 UTC, JanuarAsprilla commented on src/januar_asprilla/react/A2/src/Components/mainComponent/index.jsx
> +        <NoticeSectionsCenter>
corregido

2024-01-04 06:28 UTC, JanuarAsprilla commented on src/januar_asprilla/react/A2/src/Components/mainComponent/index.jsx
> +          <Captionections>Fast Forward</Captionections>
correcion realizada

2024-01-04 16:25 UTC, wfercanas approved these changes

2024-01-04 16:25 UTC, merged