lo/A2/New-york-times-react
selsa-inube/bootcamp pull request #638
Opened 2023-12-29 01:46 UTC by LinconOssa

2024-01-02 15:51 UTC, wfercanas requested changes

2024-01-02 15:51 UTC, wfercanas commented on src/Lincon/react/A2/src/components/Article/index.jsx
> +  StyleSubtitle,
Dejar todo como `Styled` o todo como `Style`, pero no mezclar.
Se sugiere dejar `Styled`.

2024-01-02 15:51 UTC, wfercanas commented on src/Lincon/react/A2/src/components/Article/styles.js
> +const StyledContenedorTwo = styled.div`
No hacer spanglish. Sería `StyledContainerOne`

2024-01-02 15:51 UTC, wfercanas commented on src/Lincon/react/A2/src/components/ContainerTarjeta/index.jsx
> +  StyleClock,
StyledClock

2024-01-02 15:51 UTC, wfercanas commented on src/Lincon/react/A2/src/components/Footer/index.jsx
> +        <CartContainer background={"#ca485b"}>
En lugar de pasar directamente el hexadecimal, es preferible que cree una variable que guarde ese valor y más bien luego le pasa la variable a la prop. Con eso luego si hay cambios sólo tiene que cambiar el valor de la variable y no venir a todo el jsx a hacer cambios línea por línea.

2024-01-02 15:51 UTC, wfercanas commented on src/Lincon/react/A2/src/components/Footer/index.jsx
> +        <CartContainer background={"#ca485b"}>
Todas estas `CardContainer` las puede generar haciendo uso de `map`. Guarda la información de cada card en un arreglo de objetos y de esa manera no tiene que crear a mano el jsx de cada una de las cards.

2024-01-02 15:51 UTC, wfercanas commented on src/Lincon/react/A2/src/components/Header/index.jsx
> +  { label: "World", link: "#" },
Agregue aquí un id para cada ítem. Con eso luego no tiene que usar el `index` del `map` para agregar la `key`, ya que es mala práctica.

2024-01-02 15:51 UTC, wfercanas commented on src/Lincon/react/A2/src/components/Lists/index.jsx
> +      {items.map((item, index) => (
No usar el `index` para asignar la `key`

2024-01-02 15:51 UTC, wfercanas commented on src/Lincon/react/A2/src/components/Nav/index.jsx
> +      <StyledParrafo>Business</StyledParrafo>
No usar Spanglish

2024-01-03 23:00 UTC, LinconOssa commented on src/Lincon/react/A2/src/components/Article/index.jsx
> +  StyleSubtitle,
![image](https://github.com/selsa-inube/bootcamp/assets/103295353/1f7698ee-836f-40a4-9cf0-f6a63bcd3741)
Listo

2024-01-03 23:00 UTC, LinconOssa commented on src/Lincon/react/A2/src/components/Article/styles.js
> +const StyledContenedorTwo = styled.div`
![image](https://github.com/selsa-inube/bootcamp/assets/103295353/aa87f4eb-9083-47d7-b31f-e09bc30b74db)
Listo

2024-01-03 23:00 UTC, LinconOssa commented on src/Lincon/react/A2/src/components/ContainerTarjeta/index.jsx
> +  StyleClock,
![image](https://github.com/selsa-inube/bootcamp/assets/103295353/0b6ad9a3-cb0b-42d4-b52f-ea8daef492ad)
Listo

2024-01-03 23:00 UTC, LinconOssa commented on src/Lincon/react/A2/src/components/Footer/index.jsx
> +        <CartContainer background={"#ca485b"}>
![image](https://github.com/selsa-inube/bootcamp/assets/103295353/15d823e9-bd12-47db-85c1-db8622b22989)
Listo

2024-01-03 23:00 UTC, LinconOssa commented on src/Lincon/react/A2/src/components/Footer/index.jsx
> +        <CartContainer background={"#ca485b"}>
![image](https://github.com/selsa-inube/bootcamp/assets/103295353/3726551f-35cd-4a84-9fba-daa1af15a91a)

2024-01-03 23:00 UTC, LinconOssa commented on src/Lincon/react/A2/src/components/Header/index.jsx
> +  { label: "World", link: "#" },
![image](https://github.com/selsa-inube/bootcamp/assets/103295353/d0afe63b-476c-4319-a08f-bbbbfa3f10b9)
Listo

2024-01-03 23:00 UTC, LinconOssa commented on src/Lincon/react/A2/src/components/Lists/index.jsx
> +      {items.map((item, index) => (
![image](https://github.com/selsa-inube/bootcamp/assets/103295353/8eb50efb-c791-426e-9f45-cf6d1d80c29b)
Listo

2024-01-03 23:01 UTC, LinconOssa commented on src/Lincon/react/A2/src/components/Nav/index.jsx
> +      <StyledParrafo>Business</StyledParrafo>
![image](https://github.com/selsa-inube/bootcamp/assets/103295353/216b57e5-b18f-4e2c-8bcf-475ac9f76710)
Listo

2024-01-04 16:30 UTC, wfercanas approved these changes

2024-01-04 16:30 UTC, merged