cr/2/nyt in react
selsa-inube/bootcamp pull request #652
Opened 2024-01-03 04:57 UTC by carin91

2024-01-03 16:12 UTC, wfercanas requested changes

2024-01-03 16:12 UTC, wfercanas commented on src/carin/react/A2/src/components/footer/index.tsx
> +      <nav id="left-side-footer">
Aquí como estamos implementando styled-components para lograr que los estilos se apliquen sólo a un componente particular, la idea es no usar ids o clases sino crear styled-components.

**Excepción**: las clases necesarias para poder insertar un ícono pueden mantenerse.

2024-01-03 16:12 UTC, wfercanas commented on src/carin/react/A2/src/components/footer/index.tsx
> +          </li>
El lugar de escribir uno por uno los items de la lista en el jsx, puede crear un array de objetos y construir la lista con un `map()`

2024-01-03 16:12 UTC, wfercanas commented on src/carin/react/A2/src/components/header/index.tsx
> +          <button>SUBSCRIBE</button>
Cree un componente `<Button />` cuyas props permitan renderizar estos dos botones con sus diferentes variantes.

2024-01-03 16:12 UTC, wfercanas commented on src/carin/react/A2/src/components/main/fastForwardArticles/styles.ts
> +const StyledFastForwardArticles = styled.section`
Si estos componentes se van a llamar luego `FastForwardArticles` no es mejor usar un `styled.article`?

2024-01-03 16:12 UTC, wfercanas commented on src/carin/react/A2/src/components/main/latestNewsArticles/index.tsx
> +      <a className="continue-reading">Continue Reading</a>
Evitar el uso de clases

2024-01-03 16:12 UTC, wfercanas commented on src/carin/react/A2/src/components/main/navBarSections/index.tsx
> +        </li>
Estos ítems de lista los puede renderizar haciendo un `map()` en lugar de escribir a mano cada ítem en el jsx.

2024-01-03 16:12 UTC, wfercanas commented on src/carin/react/A2/src/components/main/navTopics/index.tsx
> +        </li>
Utilizar `map()` para renderizar la lista

2024-01-04 11:31 UTC, carin91 commented on src/carin/react/A2/src/components/aside/Aside.stories.tsx
attended

2024-01-04 11:32 UTC, carin91 commented on src/carin/react/A2/src/pages/home/index.tsx
attended.
The app was loading the styles from default css files, i deleted them and deleted the line that was charging it on the app.tsx and main.tsx

2024-01-04 12:15 UTC, carin91 commented on src/carin/react/A2/src/components/footer/index.tsx
> +          </li>
attended

2024-01-04 12:15 UTC, carin91 commented on src/carin/react/A2/src/components/main/navBarSections/index.tsx
> +        </li>
attended

2024-01-04 12:15 UTC, carin91 commented on src/carin/react/A2/src/components/main/navTopics/index.tsx
> +        </li>
attended

2024-01-04 12:39 UTC, carin91 commented on src/carin/react/A2/src/components/main/latestNewsArticles/index.tsx
> +      <a className="continue-reading">Continue Reading</a>
attended

2024-01-04 12:46 UTC, carin91 commented on src/carin/react/A2/src/components/main/fastForwardArticles/styles.ts
> +const StyledFastForwardArticles = styled.section`
attended.

In the previous version (nyt html-css) i assigned it a section tag because i though "this is not an article in the sense of tags because it has no sense in other context", however, in the sense of newspaper those are articles or references to them. However, reevaluating my toughts i changed it to article tag.

2024-01-04 12:58 UTC, carin91 commented on src/carin/react/A2/src/components/header/index.tsx
> +          <button>SUBSCRIBE</button>
Attended

![image](https://github.com/selsa-inube/bootcamp/assets/123512032/a17488cb-3047-4e19-809b-1b09850b7496)

2024-01-04 12:59 UTC, carin91 commented on src/carin/react/A2/src/components/footer/index.tsx
> +      <nav id="left-side-footer">
attended

2024-01-04 16:49 UTC, wfercanas approved these changes

2024-01-04 16:49 UTC, merged